// Forge-Change
using System.Linq;
using System.Numerics;
using Content.Client._Wega.Stylesheets;
using Content.Client.GameTicking.Managers;
using Content.Shared.SecApartment;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Wega.Security.SecApartment;

[Virtual]
[GenerateTypedNameReferences]
public partial class SecApartmentWindow : BaseWindow
{
    private static readonly (string Title, string Department)[] DebugSquadDepartments =
    {
        ("ТСФ", "TSF"),
        ("НаноТразен", "NanoTrasen"),
        ("СИВ", "Empire"),
        ("СССП", "UnionOfSovietSocialistPlanets"),
        ("Ренегаты", "Renegates")
    };

    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly SpriteSystem _sprite;

    private readonly SecApartmentStyles _styles;
    private string _station = Loc.GetString("sec-apartment-unknown");
    private string _activeTheme = "Security";
    private bool UsesRecoloredTheme => _activeTheme != "Security";
    private bool _showAliveUnassigned = true;
    private bool _showDeadUnassigned = true;
    private readonly Dictionary<string, bool> _showDebugSquadCategories = new()
    {
        ["TSF"] = true,
        ["NanoTrasen"] = true,
        ["CIV"] = true,
        ["USSP"] = true,
        ["Renegates"] = true
    };
    private List<CrewMemberInfo> _lastUnassignedCrew = new();
    private List<Squad> _lastSquads = new();
    private Dictionary<string, SquadEntry> _squadEntries = new();
    private Dictionary<string, CrewMemberInfo> _lastCrewData = new();
    private Dictionary<string, string> _nameDrafts = new();
    private Dictionary<string, string> _descriptionDrafts = new();
    private Dictionary<NetEntity, TimerEntryControl> _timerControls = new();
    private readonly Dictionary<int, string> _debugDepartmentIds = new();
    private string _selectedDebugDepartment = DebugSquadDepartments[0].Department;
    private Stylesheet? _previousStylesheet;

    public Action<string, string>? OnCreateSquad;
    public Action<string, string>? OnRenameSquad;
    public Action<string>? OnDeleteSquad;
    public Action<string, string>? OnUpdateSquadDescription;
    public Action<string, SquadStatus>? OnChangeSquadStatus;
    public Action<string, string>? OnAddMemberToSquad;
    public Action<string, string>? OnRemoveMemberFromSquad;
    public Action<string, SquadIconNum>? OnChangeSquadIcon;
    public Action<NetEntity>? OnRemoveTimer;

    public SecApartmentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entitySystem.GetEntitySystem<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _styles = new SecApartmentStyles(_resCache);
        _previousStylesheet = _ui.Stylesheet;

        SetupAllStyles();

        OnClose += RestorePreviousStylesheet;
        CloseButton.OnPressed += _ => Close();

        NewSquadName.OnTextChanged += OnSquadNameTextChanged;
        SetupDebugDepartmentDropdown();

        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
        CreateSquadButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(NewSquadName.Text))
            {
                var squadName = FormattedMessage.RemoveMarkupPermissive(NewSquadName.Text);
                if (squadName.Length > 16) squadName = squadName[..16];

                OnCreateSquad?.Invoke(squadName, DebugSquadDepartmentDropdown.Visible ? _selectedDebugDepartment : string.Empty);
                NewSquadName.Text = string.Empty;
                CreateSquadButton.Disabled = true;
            }
        };
    }

    private void SetupDebugDepartmentDropdown()
    {
        DebugSquadDepartmentDropdown.Clear();
        _debugDepartmentIds.Clear();

        foreach (var (title, department) in DebugSquadDepartments)
        {
            var index = DebugSquadDepartmentDropdown.ItemCount;
            DebugSquadDepartmentDropdown.AddItem(title);
            _debugDepartmentIds[index] = department;
        }

        DebugSquadDepartmentDropdown.Select(0);
        DebugSquadDepartmentDropdown.OnItemSelected += args =>
        {
            DebugSquadDepartmentDropdown.SelectId(args.Id);
            if (_debugDepartmentIds.TryGetValue(args.Id, out var department))
                _selectedDebugDepartment = department;
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        StationLabel.Text = Loc.GetString("sec-apartment-ui-mark", ("time", stationTime.ToString("hh\\:mm\\:ss")), ("station", _station));
    }

    private void SetupAllStyles()
    {
        SetupBasicStyles();
        SetupTabContainer();
    }

    private void SetupBasicStyles()
    {
        StationLabel.FontColorOverride = SecApartmentStyles.HeadingColor;
        StationLabel.FontOverride = _styles.GetBoldFont(16);

        UnassignedCountLabel.FontColorOverride = SecApartmentStyles.TextColor;
        UnassignedCountLabel.FontOverride = _styles.GetRegularFont(13);

        SquadsCountLabel.FontColorOverride = SecApartmentStyles.TextColor;
        SquadsCountLabel.FontOverride = _styles.GetRegularFont(13);

        Footer.FontColorOverride = SecApartmentStyles.SubTextColor;
        Footer.FontOverride = _styles.GetRegularFont(11);

        StationLabel.AddStyleClass(SecApartmentStyles.StyleClassConsoleHeading);
        NewSquadName.AddStyleClass(SecApartmentStyles.StyleClassConsoleLineEdit);
        CreateSquadButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        var buttonStyleRule = SecApartmentStyles.CreateButtonRedRule(
            _styles.GetButtonRedStyle(),
            _styles.GetBoldFont(11),
            SecApartmentStyles.TabActiveColor,
            SecApartmentStyles.TabInactiveColor
        );

        var lineEditRule = SecApartmentStyles.CreateLineEditRule(
            _styles.GetLineEditStyle(),
            _styles.GetRegularFont(11),
            SecApartmentStyles.TextColor,
            SecApartmentStyles.PlaceholderColor
        );

        var optionRule = SecApartmentStyles.CreateOptionButtonRule(
            _styles.GetOptionButtonStyle(),
            _styles.GetRegularFont(11),
            SecApartmentStyles.TextColor,
            SecApartmentStyles.TabInactiveColor
        );

        var rules = new[] { buttonStyleRule, lineEditRule, optionRule };
        var stylesheet = CreateCombinedStylesheet(rules);
        UserInterfaceManager.Stylesheet = stylesheet;
    }

    private void RestorePreviousStylesheet()
    {
        UserInterfaceManager.Stylesheet = _previousStylesheet;
    }

    private void SetupTabContainer()
    {
        Tabs.SetTabTitle(0, Loc.GetString("sec-apartment-tab-squads"));
        Tabs.SetTabTitle(1, Loc.GetString("sec-apartment-tab-timers"));

        Tabs.TabFontColorOverride = SecApartmentStyles.TabActiveColor;
        Tabs.TabFontColorInactiveOverride = SecApartmentStyles.TabInactiveColor;

        var tabRule = SecApartmentStyles.CreateTabContainerRule(
            _styles.GetTabActiveStyle(),
            _styles.GetTabInactiveStyle(),
            _styles.GetPanelStyle(),
            _styles.GetBoldFont(),
            SecApartmentStyles.TabActiveColor,
            SecApartmentStyles.TabInactiveColor
        );

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private Stylesheet CreateCombinedStylesheet(StyleRule[] additionalRules)
    {
        var existingStyles = _previousStylesheet ?? _ui.Stylesheet;
        var combinedRules = new List<StyleRule>();

        if (existingStyles?.Rules != null)
            combinedRules.AddRange(existingStyles.Rules);

        combinedRules.AddRange(additionalRules);

        return new Stylesheet(combinedRules);
    }

    private void OnSquadNameTextChanged(LineEdit.LineEditEventArgs args)
    {
        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
    }

    public void UpdateState(SecApartmentUpdateState state)
    {
        _station = state.StationName?.ToUpperInvariant() ?? Loc.GetString("sec-apartment-unknown");
        ApplyTheme(state.Department);
        DebugSquadDepartmentDropdown.Visible = state.Debug;

        UpdateUnassignedList(state.UnassignedSecurity, state.Squads);
        UpdateSquadsList(state.Squads, state.Debug);

        if (UsesRecoloredTheme)
            RecolorControl(this);
    }

    public void ApplyTheme(string department)
    {
        var theme = department switch
        {
            "TSF" => "TSF",
            "NanoTrasen" => "NanoTrasen",
            "Empire" => "Empire",
            "UnionOfSovietSocialistPlanets" => "USSP",
            "Renegates" => "Renegates",
            _ => "Security"
        };
        var isFactionTablet = department != "Security";

        Logo.Visible = !isFactionTablet;
        Footer.Visible = !isFactionTablet;

        if (_activeTheme == theme)
            return;

        _activeTheme = theme;

        switch (theme)
        {
            case "TSF":
                ApplyBlueStylesheet();
                RecolorControl(this);
                Tabs.TabFontColorOverride = Color.FromHex("#44aaff");
                Tabs.TabFontColorInactiveOverride = Color.FromHex("#88ccff");
                break;
            case "Renegates":
                ApplyOrangeStylesheet();
                RecolorControl(this);
                Tabs.TabFontColorOverride = Color.FromHex("#ff9a3c");
                Tabs.TabFontColorInactiveOverride = Color.FromHex("#d8955d");
                break;
            case "NanoTrasen":
                ApplyNanoTrasenStylesheet();
                RecolorControl(this);
                Tabs.TabFontColorOverride = Color.FromHex("#00b7ff");
                Tabs.TabFontColorInactiveOverride = Color.FromHex("#6bdcff");
                break;
            case "Empire":
                ApplyEmpireStylesheet();
                RecolorControl(this);
                Tabs.TabFontColorOverride = Color.FromHex("#c89a5a");
                Tabs.TabFontColorInactiveOverride = Color.FromHex("#d8b98a");
                break;
            case "USSP":
                ApplyUsspStylesheet();
                RecolorControl(this);
                Tabs.TabFontColorOverride = Color.FromHex("#d2b48c");
                Tabs.TabFontColorInactiveOverride = Color.FromHex("#e0c7a1");
                break;
        }
    }

    private void ApplyBlueStylesheet()
    {
        var buttonStyleRule = SecApartmentStyles.CreateButtonRedRule(
            CreateBlueStyleBox("#003d66", "#44aaff", new Thickness(1), new Thickness(8, 4, 8, 4)),
            _styles.GetBoldFont(11),
            Color.FromHex("#44aaff"),
            Color.FromHex("#88ccff"));

        var lineEditRule = SecApartmentStyles.CreateLineEditRule(
            CreateBlueStyleBox("#001426", "#44aaff", new Thickness(1), new Thickness(4, 2, 4, 2)),
            _styles.GetRegularFont(11),
            Color.FromHex("#99ddff"),
            Color.FromHex("#66bbee"));

        var optionRule = SecApartmentStyles.CreateOptionButtonRule(
            CreateBlueStyleBox("#001833", "#44aaff", new Thickness(1), new Thickness(6, 3, 6, 3)),
            _styles.GetRegularFont(11),
            Color.FromHex("#99ddff"),
            Color.FromHex("#88ccff"));

        UserInterfaceManager.Stylesheet = CreateCombinedStylesheet(new[] { buttonStyleRule, lineEditRule, optionRule });

        var tabRule = SecApartmentStyles.CreateTabContainerRule(
            CreateBlueStyleBox("#001f44", "#44aaff", new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateBlueStyleBox("#001426", "#88ccff", new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateBlueStyleBox("#000f1f", "#44aaff", new Thickness(2), new Thickness(5, 5, 5, 5)),
            _styles.GetBoldFont(),
            Color.FromHex("#44aaff"),
            Color.FromHex("#88ccff"));

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private void ApplyOrangeStylesheet()
    {
        var buttonStyleRule = SecApartmentStyles.CreateButtonRedRule(
            CreateThemedStyleBox("#6b2d12", "#ff9a3c", new Thickness(1), new Thickness(8, 4, 8, 4)),
            _styles.GetBoldFont(11),
            Color.FromHex("#ff9a3c"),
            Color.FromHex("#d8955d"));

        var lineEditRule = SecApartmentStyles.CreateLineEditRule(
            CreateThemedStyleBox("#241307", "#d66a22", new Thickness(1), new Thickness(4, 2, 4, 2)),
            _styles.GetRegularFont(11),
            Color.FromHex("#ffd0a0"),
            Color.FromHex("#b86a32"));

        var optionRule = SecApartmentStyles.CreateOptionButtonRule(
            CreateThemedStyleBox("#301706", "#d66a22", new Thickness(1), new Thickness(6, 3, 6, 3)),
            _styles.GetRegularFont(11),
            Color.FromHex("#ffd0a0"),
            Color.FromHex("#d8955d"));

        UserInterfaceManager.Stylesheet = CreateCombinedStylesheet(new[] { buttonStyleRule, lineEditRule, optionRule });

        var tabRule = SecApartmentStyles.CreateTabContainerRule(
            CreateThemedStyleBox("#4d220a", "#ff9a3c", new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateThemedStyleBox("#241307", "#d8955d", new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateThemedStyleBox("#1a0d05", "#d66a22", new Thickness(2), new Thickness(5, 5, 5, 5)),
            _styles.GetBoldFont(),
            Color.FromHex("#ff9a3c"),
            Color.FromHex("#d8955d"));

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private void ApplyNanoTrasenStylesheet()
    {
        ApplyPaletteStylesheet(
            "#004466", "#001626", "#002b44",
            "#00395c", "#001c2e", "#000f1a",
            "#00b7ff", "#6bdcff", "#a8f0ff", "#44aacc");
    }

    private void ApplyEmpireStylesheet()
    {
        ApplyPaletteStylesheet(
            "#4f3418", "#1f1409", "#2e1c0d",
            "#3b2510", "#1f1409", "#160d06",
            "#c89a5a", "#d8b98a", "#ffe2b0", "#b78a54");
    }

    private void ApplyUsspStylesheet()
    {
        ApplyPaletteStylesheet(
            "#4a3926", "#21180e", "#332616",
            "#3d2d1b", "#21180e", "#171006",
            "#d2b48c", "#e0c7a1", "#fff0d0", "#b99b74");
    }

    private void ApplyPaletteStylesheet(
        string buttonBackground,
        string lineEditBackground,
        string optionBackground,
        string tabActiveBackground,
        string tabInactiveBackground,
        string panelBackground,
        string accent,
        string inactive,
        string text,
        string placeholder)
    {
        var buttonStyleRule = SecApartmentStyles.CreateButtonRedRule(
            CreateThemedStyleBox(buttonBackground, accent, new Thickness(1), new Thickness(8, 4, 8, 4)),
            _styles.GetBoldFont(11),
            Color.FromHex(accent),
            Color.FromHex(inactive));

        var lineEditRule = SecApartmentStyles.CreateLineEditRule(
            CreateThemedStyleBox(lineEditBackground, accent, new Thickness(1), new Thickness(4, 2, 4, 2)),
            _styles.GetRegularFont(11),
            Color.FromHex(text),
            Color.FromHex(placeholder));

        var optionRule = SecApartmentStyles.CreateOptionButtonRule(
            CreateThemedStyleBox(optionBackground, accent, new Thickness(1), new Thickness(6, 3, 6, 3)),
            _styles.GetRegularFont(11),
            Color.FromHex(text),
            Color.FromHex(inactive));

        UserInterfaceManager.Stylesheet = CreateCombinedStylesheet(new[] { buttonStyleRule, lineEditRule, optionRule });

        var tabRule = SecApartmentStyles.CreateTabContainerRule(
            CreateThemedStyleBox(tabActiveBackground, accent, new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateThemedStyleBox(tabInactiveBackground, inactive, new Thickness(2, 2, 2, 0), new Thickness(10, 5, 10, 5)),
            CreateThemedStyleBox(panelBackground, accent, new Thickness(2), new Thickness(5, 5, 5, 5)),
            _styles.GetBoldFont(),
            Color.FromHex(accent),
            Color.FromHex(inactive));

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private static StyleBoxFlat CreateBlueStyleBox(string background, string border, Thickness borderThickness, Thickness contentMargin)
    {
        return CreateThemedStyleBox(background, border, borderThickness, contentMargin);
    }

    private static StyleBoxFlat CreateThemedStyleBox(string background, string border, Thickness borderThickness, Thickness contentMargin)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = borderThickness,
            ContentMarginLeftOverride = contentMargin.Left,
            ContentMarginRightOverride = contentMargin.Right,
            ContentMarginTopOverride = contentMargin.Top,
            ContentMarginBottomOverride = contentMargin.Bottom
        };
    }

    private void RecolorControl(Control control)
    {
        if (control is Label label)
        {
            if (label.FontColorOverride is { } fontColor)
                label.FontColorOverride = RecolorUiColor(fontColor);
        }

        control.Modulate = RecolorUiColor(control.Modulate);
        if (control.ModulateSelfOverride is { } selfModulate)
            control.ModulateSelfOverride = RecolorUiColor(selfModulate);

        if (control is PanelContainer { PanelOverride: StyleBoxFlat style })
            RecolorStyle(style);

        foreach (var child in control.Children)
            RecolorControl(child);
    }

    private void RecolorStyle(StyleBoxFlat style)
    {
        style.BackgroundColor = RecolorUiColor(style.BackgroundColor);
        style.BorderColor = RecolorUiColor(style.BorderColor);
    }

    private Color RecolorUiColor(Color color)
    {
        return _activeTheme switch
        {
            "Renegates" => RecolorUiColorOrange(color),
            "NanoTrasen" => RecolorUiColorNanoTrasen(color),
            "Empire" => RecolorUiColorEmpire(color),
            "USSP" => RecolorUiColorUssp(color),
            _ => RecolorUiColorBlue(color)
        };
    }

    private static Color RecolorUiColorBlue(Color color)
    {
        if (color == Color.FromHex("#ff0000") || color == Color.FromHex("#ff3333"))
            return Color.FromHex("#3399ff");

        if (color == Color.FromHex("#ff4444") || color == SecApartmentStyles.TabActiveColor)
            return Color.FromHex("#44aaff");

        if (color == Color.FromHex("#ff6666") || color == SecApartmentStyles.PlaceholderColor)
            return Color.FromHex("#66bbee");

        if (color == Color.FromHex("#ff8888") || color == SecApartmentStyles.TabInactiveColor || color == SecApartmentStyles.SubTextColor)
            return Color.FromHex("#88ccff");

        if (color == Color.FromHex("#ff9999") || color == SecApartmentStyles.TextColor)
            return Color.FromHex("#99ddff");

        if (color == Color.FromHex("#ff9933"))
            return Color.FromHex("#66ccff");

        if (color == Color.FromHex("#BB2222"))
            return Color.FromHex("#225fbb");

        if (color == Color.FromHex("#990000"))
            return Color.FromHex("#0066aa");

        if (color == Color.FromHex("#660000"))
            return Color.FromHex("#003d66");

        if (color == Color.FromHex("#552222"))
            return Color.FromHex("#17375c");

        if (color == Color.FromHex("#4a1a1a"))
            return Color.FromHex("#123150");

        if (color == Color.FromHex("#441111"))
            return Color.FromHex("#102844");

        if (color == Color.FromHex("#440000"))
            return Color.FromHex("#001f44");

        if (color == Color.FromHex("#3a0f0f"))
            return Color.FromHex("#0f2b46");

        if (color == Color.FromHex("#330000"))
            return Color.FromHex("#001833");

        if (color == Color.FromHex("#2a0a0a"))
            return Color.FromHex("#0a2238");

        if (color == Color.FromHex("#220000"))
            return Color.FromHex("#001426");

        if (color == Color.FromHex("#1a0a0a"))
            return Color.FromHex("#081827");

        if (color == Color.FromHex("#110000"))
            return Color.FromHex("#000f1f");

        return color;
    }

    private static Color RecolorUiColorOrange(Color color)
    {
        if (color == Color.FromHex("#ff0000") || color == Color.FromHex("#ff3333"))
            return Color.FromHex("#e87922");

        if (color == Color.FromHex("#ff4444") || color == SecApartmentStyles.TabActiveColor)
            return Color.FromHex("#ff9a3c");

        if (color == Color.FromHex("#ff6666") || color == SecApartmentStyles.PlaceholderColor)
            return Color.FromHex("#b86a32");

        if (color == Color.FromHex("#ff8888") || color == SecApartmentStyles.TabInactiveColor || color == SecApartmentStyles.SubTextColor)
            return Color.FromHex("#d8955d");

        if (color == Color.FromHex("#ff9999") || color == SecApartmentStyles.TextColor)
            return Color.FromHex("#ffd0a0");

        if (color == Color.FromHex("#ff9933"))
            return Color.FromHex("#ffb05c");

        if (color == Color.FromHex("#BB2222"))
            return Color.FromHex("#8a3f12");

        if (color == Color.FromHex("#990000"))
            return Color.FromHex("#7a350f");

        if (color == Color.FromHex("#660000"))
            return Color.FromHex("#4d220a");

        if (color == Color.FromHex("#552222"))
            return Color.FromHex("#4a2512");

        if (color == Color.FromHex("#4a1a1a"))
            return Color.FromHex("#3f1f0f");

        if (color == Color.FromHex("#441111"))
            return Color.FromHex("#3a2115");

        if (color == Color.FromHex("#440000"))
            return Color.FromHex("#301706");

        if (color == Color.FromHex("#3a0f0f"))
            return Color.FromHex("#332017");

        if (color == Color.FromHex("#330000"))
            return Color.FromHex("#241307");

        if (color == Color.FromHex("#2a0a0a"))
            return Color.FromHex("#24160d");

        if (color == Color.FromHex("#220000"))
            return Color.FromHex("#1f1006");

        if (color == Color.FromHex("#1a0a0a"))
            return Color.FromHex("#1a0d05");

        if (color == Color.FromHex("#110000"))
            return Color.FromHex("#120803");

        return color;
    }

    private static Color RecolorUiColorNanoTrasen(Color color)
    {
        return RecolorUiColorPalette(
            color,
            "#00b7ff", "#00a2e8", "#44aacc", "#6bdcff", "#a8f0ff", "#7bdfff",
            "#006b9f", "#004f78", "#003b5c", "#00324d", "#002b44", "#002438",
            "#001c2e", "#001626", "#00111c", "#000f1a");
    }

    private static Color RecolorUiColorEmpire(Color color)
    {
        return RecolorUiColorPalette(
            color,
            "#c89a5a", "#b8874a", "#b78a54", "#d8b98a", "#ffe2b0", "#e8bd80",
            "#6b4722", "#5a3a1b", "#4a3017", "#412914", "#38220f", "#2e1c0d",
            "#26180b", "#1f1409", "#170f08", "#120b05");
    }

    private static Color RecolorUiColorUssp(Color color)
    {
        return RecolorUiColorPalette(
            color,
            "#d2b48c", "#c39f73", "#b99b74", "#e0c7a1", "#fff0d0", "#d8bd91",
            "#6a5135", "#5a432b", "#4a3926", "#42321f", "#3a2c1b", "#332616",
            "#2a1f12", "#21180e", "#1b1309", "#171006");
    }

    private static Color RecolorUiColorPalette(
        Color color,
        string strong,
        string active,
        string placeholder,
        string inactive,
        string text,
        string warm,
        string brightPanel,
        string border,
        string deep,
        string mid,
        string entry,
        string tab,
        string dark,
        string input,
        string panel,
        string darkest)
    {
        if (color == Color.FromHex("#ff0000") || color == Color.FromHex("#ff3333"))
            return Color.FromHex(strong);

        if (color == Color.FromHex("#ff4444") || color == SecApartmentStyles.TabActiveColor)
            return Color.FromHex(active);

        if (color == Color.FromHex("#ff6666") || color == SecApartmentStyles.PlaceholderColor)
            return Color.FromHex(placeholder);

        if (color == Color.FromHex("#ff8888") || color == SecApartmentStyles.TabInactiveColor || color == SecApartmentStyles.SubTextColor)
            return Color.FromHex(inactive);

        if (color == Color.FromHex("#ff9999") || color == SecApartmentStyles.TextColor)
            return Color.FromHex(text);

        if (color == Color.FromHex("#ff9933"))
            return Color.FromHex(warm);

        if (color == Color.FromHex("#BB2222"))
            return Color.FromHex(brightPanel);

        if (color == Color.FromHex("#990000"))
            return Color.FromHex(border);

        if (color == Color.FromHex("#660000"))
            return Color.FromHex(deep);

        if (color == Color.FromHex("#552222"))
            return Color.FromHex(mid);

        if (color == Color.FromHex("#4a1a1a"))
            return Color.FromHex(entry);

        if (color == Color.FromHex("#441111"))
            return Color.FromHex(tab);

        if (color == Color.FromHex("#440000"))
            return Color.FromHex(dark);

        if (color == Color.FromHex("#3a0f0f"))
            return Color.FromHex(mid);

        if (color == Color.FromHex("#330000"))
            return Color.FromHex(input);

        if (color == Color.FromHex("#2a0a0a"))
            return Color.FromHex(entry);

        if (color == Color.FromHex("#220000"))
            return Color.FromHex(panel);

        if (color == Color.FromHex("#1a0a0a"))
            return Color.FromHex(darkest);

        if (color == Color.FromHex("#110000"))
            return Color.FromHex(darkest);

        return color;
    }

    public void UpdateSensorStatuses(SensorStatusUpdateState sensorState)
    {
        foreach (var squadEntry in _squadEntries.Values)
        {
            squadEntry.UpdateSensorStatuses(sensorState.MemberStatuses, sensorState.SquadLocations);
        }

        if (UsesRecoloredTheme)
            RecolorControl(this);
    }

    public void UpdateTimerState(TimerUpdateState state)
    {
        UpdateTimersList(state.Timers);

        if (UsesRecoloredTheme)
            RecolorControl(this);
    }

    private void UpdateUnassignedList(List<CrewMemberInfo> unassigned, List<Squad> squads)
    {
        _lastUnassignedCrew = unassigned;
        _lastSquads = squads;
        UnassignedCountLabel.Text = unassigned.Count.ToString();
        UnassignedContainer.Children.Clear();

        var alive = unassigned
            .Where(member => member.SensorStatus?.IsAlive == true)
            .ToList();
        var dead = unassigned
            .Where(member => member.SensorStatus?.IsAlive != true)
            .ToList();

        AddUnassignedCategory(
            Loc.GetString("sec-apartment-ui-unassigned-alive"),
            alive,
            squads,
            _showAliveUnassigned,
            expanded => _showAliveUnassigned = expanded);

        AddUnassignedCategory(
            Loc.GetString("sec-apartment-ui-unassigned-dead"),
            dead,
            squads,
            _showDeadUnassigned,
            expanded => _showDeadUnassigned = expanded);

        if (UsesRecoloredTheme)
            RecolorControl(UnassignedContainer);
    }

    private void AddUnassignedCategory(
        string title,
        List<CrewMemberInfo> members,
        List<Squad> squads,
        bool expanded,
        Action<bool> setExpanded)
    {
        var categoryContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5)
        };

        var header = new Button
        {
            Text = $"{(expanded ? "[-]" : "[+]")} {title} ({members.Count})",
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left
        };
        header.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        header.OnPressed += _ =>
        {
            setExpanded(!expanded);
            UpdateUnassignedList(_lastUnassignedCrew, _lastSquads);
        };

        categoryContainer.AddChild(header);

        if (expanded)
        {
            foreach (var member in members)
                categoryContainer.AddChild(CreateUnassignedCrewEntry(member, squads));
        }

        UnassignedContainer.AddChild(categoryContainer);
    }

    private CrewMemberEntry CreateUnassignedCrewEntry(CrewMemberInfo member, List<Squad> squads)
    {
        SpriteSpecifier? iconSpecifier = null;
        if (_prototypeManager.HasIndex<JobIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<JobIconPrototype>(member.JobIcon).Icon;
        else if (_prototypeManager.HasIndex<StatusIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<StatusIconPrototype>(member.JobIcon).Icon;

        var entry = new CrewMemberEntry(member, squads, iconSpecifier, _sprite, _styles);
        entry.OnAssignPressed += squadId =>
            OnAddMemberToSquad?.Invoke(squadId, member.MemberId);
        return entry;
    }

    private void UpdateSquadsList(List<Squad> squads, bool debug)
    {
        _nameDrafts = _squadEntries
            .Where(pair => pair.Value.IsEditingName)
            .ToDictionary(pair => pair.Key, pair => pair.Value.NameDraft);
        _descriptionDrafts = _squadEntries
            .Where(pair => pair.Value.IsEditingDescription)
            .ToDictionary(pair => pair.Key, pair => pair.Value.DescriptionDraft);

        SquadsCountLabel.Text = squads.Count.ToString();
        SquadsContainer.Children.Clear();
        _squadEntries.Clear();

        if (debug)
        {
            AddSquadCategory("TSF", "ТСФ", squads.Where(squad => squad.Department == "TSF").ToList(), debug);
            AddSquadCategory("NanoTrasen", "НаноТразен", squads.Where(IsNanoTrasenSquad).ToList(), debug);
            AddSquadCategory("CIV", "СИВ", squads.Where(IsCivilianSquad).ToList(), debug);
            AddSquadCategory("USSP", "СССП", squads.Where(IsUsspSquad).ToList(), debug);
            AddSquadCategory("Renegates", "Ренегаты", squads.Where(squad => squad.Department == "Renegates").ToList(), debug);
            return;
        }

        foreach (var squad in squads)
            AddSquadEntry(squad);
    }

    private void AddSquadCategory(string key, string title, List<Squad> squads, bool debug)
    {
        var expanded = _showDebugSquadCategories.GetValueOrDefault(key, true);
        var categoryContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5)
        };

        var header = new Button
        {
            Text = $"{(expanded ? "[-]" : "[+]")} {title} ({squads.Count})",
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left
        };
        header.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        header.OnPressed += _ =>
        {
            _showDebugSquadCategories[key] = !expanded;
            UpdateSquadsList(_lastSquads, debug);
        };

        categoryContainer.AddChild(header);

        if (expanded)
        {
            foreach (var squad in squads)
                categoryContainer.AddChild(CreateSquadEntry(squad));
        }

        SquadsContainer.AddChild(categoryContainer);
    }

    private void AddSquadEntry(Squad squad)
    {
        SquadsContainer.AddChild(CreateSquadEntry(squad));
    }

    private SquadEntry CreateSquadEntry(Squad squad)
    {
        var entry = new SquadEntry(squad, _styles, _prototypeManager, _sprite);
        entry.OnIconChanged += iconId =>
            OnChangeSquadIcon?.Invoke(squad.SquadId, iconId);
        entry.OnRenamePressed += newName =>
        {
            var cleanName = FormattedMessage.RemoveMarkupPermissive(newName);
            if (cleanName.Length > 16) cleanName = cleanName[..16];

            OnRenameSquad?.Invoke(squad.SquadId, cleanName);
        };
        entry.OnDeletePressed += () =>
            OnDeleteSquad?.Invoke(squad.SquadId);
        entry.OnUpdateDescriptionPressed += description =>
            OnUpdateSquadDescription?.Invoke(squad.SquadId, description);
        entry.OnStatusChanged += status =>
            OnChangeSquadStatus?.Invoke(squad.SquadId, status);
        entry.OnRemoveMemberPressed += memberId =>
            OnRemoveMemberFromSquad?.Invoke(squad.SquadId, memberId);

        _squadEntries[squad.SquadId] = entry;

        foreach (var member in squad.Members)
            _lastCrewData[member.MemberId] = member;

        if (_nameDrafts.TryGetValue(squad.SquadId, out var nameDraft))
            entry.RestoreNameEdit(nameDraft);

        if (_descriptionDrafts.TryGetValue(squad.SquadId, out var draft))
            entry.RestoreDescriptionEdit(draft);

        return entry;
    }

    private static bool IsNanoTrasenSquad(Squad squad)
    {
        return squad.Department is "Security" or "NanoTrasen" or "Command";
    }

    private static bool IsCivilianSquad(Squad squad)
    {
        return squad.Department is "CIV" or "Empire";
    }

    private static bool IsUsspSquad(Squad squad)
    {
        return squad.Department is "USSP" or "СССП" or "UnionOfSovietSocialistPlanets";
    }

    private void UpdateTimersList(List<TimerEntry> timers)
    {
        TimersCountLabel.Text = timers.Count.ToString();

        var toRemove = new List<NetEntity>();
        foreach (var (timerUid, control) in _timerControls)
        {
            if (!timers.Any(t => t.TimerUid == timerUid))
                toRemove.Add(timerUid);
        }

        foreach (var timerUid in toRemove)
        {
            if (_timerControls.TryGetValue(timerUid, out var control))
            {
                TimersContainer.Children.Remove(control);
                _timerControls.Remove(timerUid);
            }
        }

        foreach (var timer in timers)
        {
            if (!_timerControls.TryGetValue(timer.TimerUid, out var control))
            {
                control = new TimerEntryControl(timer, _styles);
                control.OnRemovePressed += () =>
                    OnRemoveTimer?.Invoke(timer.TimerUid);
                TimersContainer.AddChild(control);
                _timerControls[timer.TimerUid] = control;
            }
            else
            {
                control.UpdateTimer(timer);
            }
        }

        var sortedChildren = TimersContainer.Children
            .OfType<TimerEntryControl>()
            .OrderBy(t => t.RemainingTime.TotalSeconds)
            .ToList();

        TimersContainer.Children.Clear();
        foreach (var child in sortedChildren)
        {
            TimersContainer.AddChild(child);
        }
    }
}
