using Content.Shared._Forge.Bss;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

// Forge-Change-full: BSS system map
namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class BssSystemScreen : BoxContainer
{
    public event Action<string>? RequestJump;

    public BssSystemScreen()
    {
        RobustXamlLoader.Load(this);

        SystemMap.SelectionChanged += node =>
        {
            JumpButton.Disabled = node == null;
            StatusLabel.Text = node == null
                ? Loc.GetString("shuttle-console-bss-select-destination")
                : Loc.GetString("shuttle-console-bss-selected", ("sector", node.Name));
        };

        JumpButton.OnPressed += _ =>
        {
            if (SystemMap.GetSelectedNode() is { } selected)
                RequestJump?.Invoke(selected.Id);
        };
    }

    public void UpdateState(BssSystemMapState state)
    {
        SystemMap.UpdateState(state);
        NetworkTitle.Text = string.IsNullOrEmpty(state.RegionName)
            ? Loc.GetString("shuttle-console-bss-title")
            : Loc.GetString("shuttle-console-bss-network", ("network", state.RegionName));

        if (state.Error != null)
        {
            StatusLabel.Text = Loc.GetString(state.Error);
            JumpButton.Disabled = true;
            return;
        }

        if (SystemMap.GetSelectedNode() == null)
        {
            var reachable = state.Nodes.FindAll(node => node.Reachable && node.Online);
            if (reachable.Count == 1)
                SystemMap.Select(reachable[0].Id);
        }

        var selected = SystemMap.GetSelectedNode();
        JumpButton.Disabled = selected == null;
        StatusLabel.Text = selected == null
            ? Loc.GetString("shuttle-console-bss-select-destination")
            : Loc.GetString("shuttle-console-bss-selected", ("sector", selected.Name));
    }
}
