using System.Linq;
using Content.Client._Forge.Lobby.UI.Loadouts;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutGroupContainer : BoxContainer
{
    // Forge-Change-Start: grouped loadout color variants (GroupBy field)
    private const string ClosedGroupMark = "▶";
    private const string OpenedGroupMark = "▼";

    private Dictionary<string, bool> _openedGroups = new();
    // Forge-Change-End

    private readonly LoadoutGroupPrototype _groupProto;

    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public LoadoutGroupContainer(HumanoidCharacterProfile profile, RoleLoadout loadout, LoadoutGroupPrototype groupProto, ICommonSession session, IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        _groupProto = groupProto;

        RefreshLoadouts(profile, loadout, session, collection);
    }

    /// <summary>
    /// Updates button availabilities and buttons.
    /// </summary>
    public void RefreshLoadouts(HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();
        var loadoutSystem = collection.Resolve<IEntityManager>().System<LoadoutSystem>();
        RestrictionsContainer.DisposeAllChildren();

        if (_groupProto.MinLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-min-limit", ("count", _groupProto.MinLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (_groupProto.MaxLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-max-limit", ("count", _groupProto.MaxLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (protoMan.TryIndex(loadout.Role, out var roleProto) && roleProto.Points != null && loadout.Points != null)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-points-limit", ("count", loadout.Points.Value), ("max", roleProto.Points.Value)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        LoadoutsContainer.DisposeAllChildren();
        // Didn't use options because this is more robust in future.

        var selected = loadout.SelectedLoadouts[_groupProto.ID];

        foreach (var loadoutProto in _groupProto.Loadouts)
        {
            if (!protoMan.TryIndex(loadoutProto, out var loadProto))
                continue;

            // Frontier: hide loadout effects
            if (loadout.IsHidden(profile, session, loadoutProto, collection))
                continue;
            // End Frontier: hide loadout effects

            var matchingLoadout = selected.FirstOrDefault(e => e.Prototype == loadoutProto);
            var pressed = matchingLoadout != null;

            var enabled = loadout.IsValid(profile, session, loadoutProto, collection, out var reason);
            var loadoutContainer = new LoadoutContainer(loadoutProto, !enabled, reason);
            loadoutContainer.Select.Pressed = pressed;
            loadoutContainer.Text = string.IsNullOrEmpty(loadProto.Name)
                ? loadoutSystem.GetName(loadProto)
                : Loc.GetString(loadProto.Name); // Frontier: allow overriding loadout names via localization keys

            loadoutContainer.Select.OnPressed += args =>
            {
                if (args.Button.Pressed)
                    OnLoadoutPressed?.Invoke(loadoutProto);
                else
                    OnLoadoutUnpressed?.Invoke(loadoutProto);
            };

            LoadoutsContainer.AddChild(loadoutContainer);
        }

        // Frontier: loadoutGroup subgroups
        foreach (var subgroupProto in _groupProto.Subgroups)
        {
            if (!protoMan.TryIndex(subgroupProto, out var loadoutGroupProto))
                continue;

            // Forge-Change: apply GroupBy grouping to subgroup loadouts only
            AddGroupedLoadouts(loadoutGroupProto.Loadouts, profile, loadout, session, collection, loadoutSystem, protoMan);
        }
        // End Frontier
    }

    // Forge-Change-Start: grouped loadout color variants (GroupBy field)
    private void AddGroupedLoadouts(
        IEnumerable<ProtoId<LoadoutPrototype>> loadoutIds,
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        ICommonSession session,
        IDependencyCollection collection,
        LoadoutSystem loadoutSystem,
        IPrototypeManager protoMan)
    {
        var validProtos = new List<LoadoutPrototype>();

        foreach (var loadoutProto in loadoutIds)
        {
            if (!protoMan.TryIndex(loadoutProto, out var loadProto))
                continue;

            if (loadout.IsHidden(profile, session, loadoutProto, collection))
                continue;

            validProtos.Add(loadProto);
        }

        var groups = validProtos
            .GroupBy(p => string.IsNullOrEmpty(p.GroupBy) ? p.ID : p.GroupBy)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var kvp in groups)
        {
            var protos = kvp.Value;

            if (protos.Count > 1)
            {
                var uiElements = protos
                    .Select(proto =>
                    {
                        var elem = CreateLoadoutUI(proto, profile, loadout, session, collection, loadoutSystem);
                        elem.HorizontalExpand = true;
                        return elem;
                    })
                    .ToList();

                var firstElement = uiElements.FirstOrDefault(e => e.Select.Pressed) ?? uiElements[0];
                var otherElements = uiElements.Where(e => !ReferenceEquals(e, firstElement)).ToList();

                firstElement.HorizontalExpand = true;
                var subContainer = new SubLoadoutContainer
                {
                    Visible = _openedGroups.GetValueOrDefault(kvp.Key, false)
                };
                var toggle = CreateToggleButton(kvp, firstElement, subContainer);

                LoadoutsContainer.AddChild(firstElement);
                LoadoutsContainer.AddChild(subContainer);

                var subList = subContainer.Grid;
                foreach (var proto in otherElements)
                {
                    subList.AddChild(proto);
                }

                UpdateToggleColor(toggle, subList);
            }
            else
            {
                LoadoutsContainer.AddChild(
                    CreateLoadoutUI(protos[0], profile, loadout, session, collection, loadoutSystem));
            }
        }
    }

    private ToggleLoadoutButton CreateToggleButton(
        KeyValuePair<string, List<LoadoutPrototype>> kvp,
        LoadoutContainer firstElement,
        SubLoadoutContainer subContainer)
    {
        var toggle = new ToggleLoadoutButton
        {
            Text = subContainer.Visible ? OpenedGroupMark : ClosedGroupMark
        };

        toggle.OnPressed += _ =>
        {
            var willOpen = !subContainer.Visible;
            subContainer.Visible = willOpen;
            toggle.Text = willOpen ? OpenedGroupMark : ClosedGroupMark;
            _openedGroups[kvp.Key] = willOpen;
        };

        firstElement.AddChild(toggle);
        toggle.SetPositionFirst();
        return toggle;
    }

    private void UpdateToggleColor(Button toggle, BoxContainer subList)
    {
        var anyActive = subList.Children
            .OfType<LoadoutContainer>()
            .Any(c => c.Select.Pressed);

        toggle.Modulate = anyActive ? Color.Green : Color.White;
    }

    private LoadoutContainer CreateLoadoutUI(
        LoadoutPrototype proto,
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        ICommonSession session,
        IDependencyCollection collection,
        LoadoutSystem loadoutSystem)
    {
        var selected = loadout.SelectedLoadouts[_groupProto.ID];
        var pressed = selected.Any(e => e.Prototype == proto.ID);
        var enabled = loadout.IsValid(profile, session, proto.ID, collection, out var reason);
        var cont = new LoadoutContainer(proto.ID, !enabled, reason);

        cont.Text = string.IsNullOrEmpty(proto.Name)
            ? loadoutSystem.GetName(proto)
            : Loc.GetString(proto.Name);

        cont.Select.Pressed = pressed;

        cont.Select.OnPressed += args =>
        {
            if (args.Button.Pressed)
                OnLoadoutPressed?.Invoke(proto.ID);
            else
                OnLoadoutUnpressed?.Invoke(proto.ID);
        };

        return cont;
    }
    // Forge-Change-End
}
