using System.Numerics;
using Content.Client.Humanoid;
using Content.Shared._EE.Contractors;
using Content.Shared._EE.Contractors.Prototypes;
using Content.Shared._EE.Contractors.Systems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._EE.Contractors.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : BaseWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private static readonly Color PaperInk = Color.FromHex("#1A120C");
    private static readonly Color PaperMuted = Color.FromHex("#6B5535");
    private static readonly Color PdaGreen = Color.FromHex("#7CFFC8");

    private EntityUid? _photoDummy;

    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CloseButton.OnPressed += _ => Close();

        var modeGroup = new ButtonGroup();
        PaperModeButton.Group = modeGroup;
        PdaModeButton.Group = modeGroup;
        PaperModeButton.OnPressed += _ => SetPdaMode(false);
        PdaModeButton.OnPressed += _ => SetPdaMode(true);
        PhotoView.Stretch = SpriteView.StretchMode.Fit;
        PdaPhotoView.Stretch = SpriteView.StretchMode.Fit;
    }

    public void UpdateState(PassportBoundUserInterfaceState state)
    {
        var profile = state.Profile;
        ApplyTheme(profile?.Nationality);

        if (profile == null)
        {
            ShowUnregistered(state.Pid);
            return;
        }

        PhotoMissingLabel.Visible = false;
        PhotoView.Visible = true;
        PdaPhotoView.Visible = true;

        var (surname, given) = SplitName(profile.Name);
        var nationalityName = GetNationalityName(profile.Nationality);
        var code = GetNationalityCode(profile.Nationality);
        var speciesName = GetSpeciesName(profile.Species);
        var sexText = LocSex(profile.Sex);
        var yearOfBirth = SharedPassportSystem.CurrentYear - profile.Age;
        var height = GetHeightCm(profile);

        CountryLabel.Text = nationalityName.ToUpperInvariant();
        PhotoCodeLabel.Text = code;
        TypeValueLabel.Text = Loc.GetString("passport-ui-type-value");
        CodeValueLabel.Text = code;
        NumberValueLabel.Text = string.IsNullOrEmpty(state.Pid)
            ? Loc.GetString("passport-ui-unregistered")
            : state.Pid;
        SurnameLabel.Text = surname.ToUpperInvariant();
        GivenNamesLabel.Text = given;
        NationalityLabel.Text = nationalityName;
        SpeciesLabel.Text = speciesName;
        BirthLabel.Text = Loc.GetString("passport-ui-year-value", ("year", yearOfBirth));
        SexLabel.Text = sexText;
        HeightLabel.Text = Loc.GetString("passport-ui-height-value", ("height", height));
        AuthorityLabel.Text = Loc.GetString("passport-ui-authority-value", ("nationality", nationalityName));

        var flavor = profile.FlavorText?.Trim();
        var hasMarks = !string.IsNullOrEmpty(flavor);
        MarksCaptionLabel.Visible = hasMarks;
        MarksLabel.Visible = hasMarks;
        if (hasMarks)
        {
            MarksLabel.Text = flavor!.Length > 180 ? flavor[..177] + "..." : flavor;
        }

        BuildMrz(code, surname, given, state.Pid, yearOfBirth, profile.Sex);
        UpdatePdaView(profile, nationalityName, speciesName, sexText, yearOfBirth, height, state.Pid);
        ReloadPhoto(profile);
    }

    private void ShowUnregistered(string pid)
    {
        PhotoView.Visible = false;
        PdaPhotoView.Visible = false;
        PhotoMissingLabel.Visible = true;
        DeletePhotoDummy();

        CountryLabel.Text = Loc.GetString("passport-ui-unregistered").ToUpperInvariant();
        PhotoCodeLabel.Text = "---";
        TypeValueLabel.Text = Loc.GetString("passport-ui-type-value");
        CodeValueLabel.Text = "XXX";
        NumberValueLabel.Text = string.IsNullOrEmpty(pid) ? "---------------" : pid;
        SurnameLabel.Text = "-----";
        GivenNamesLabel.Text = "-----";
        NationalityLabel.Text = Loc.GetString("passport-ui-unregistered");
        SpeciesLabel.Text = "-----";
        BirthLabel.Text = "----";
        SexLabel.Text = "-----";
        HeightLabel.Text = "-----";
        AuthorityLabel.Text = Loc.GetString("passport-ui-unregistered");
        MarksCaptionLabel.Visible = false;
        MarksLabel.Visible = false;
        MrzLine1Label.Text = "P<XXX<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<";
        MrzLine2Label.Text = "<<<<<<<<<<<<<<<XXX<<<<<<<<<<<<<<<<<<<<<<";

        PdaStatusLabel.Text = Loc.GetString("passport-ui-pda-status-blank");
        PdaNameLabel.SetMessage(PdaLine("passport-ui-pda-name", Loc.GetString("passport-ui-unregistered")));
        PdaNationalityLabel.SetMessage(PdaLine("passport-ui-nationality", "-----"));
        PdaSpeciesLabel.SetMessage(PdaLine("passport-ui-species", "-----"));
        PdaSexLabel.SetMessage(PdaLine("passport-ui-sex", "-----"));
        PdaBirthLabel.SetMessage(PdaLine("passport-ui-date-of-birth", "----"));
        PdaHeightLabel.SetMessage(PdaLine("passport-ui-height", "-----"));
        PdaPidLabel.SetMessage(PdaLine("passport-ui-number", string.IsNullOrEmpty(pid) ? "-----" : pid));
        PdaAuthLabel.Text = Loc.GetString("passport-ui-pda-auth-blank");
    }

    private void UpdatePdaView(
        HumanoidCharacterProfile profile,
        string nationalityName,
        string speciesName,
        string sexText,
        int yearOfBirth,
        int height,
        string pid)
    {
        PdaStatusLabel.Text = Loc.GetString("passport-ui-pda-status-valid");
        PdaNameLabel.SetMessage(PdaLine("passport-ui-pda-name", profile.Name));
        PdaNationalityLabel.SetMessage(PdaLine("passport-ui-nationality", nationalityName));
        PdaSpeciesLabel.SetMessage(PdaLine("passport-ui-species", speciesName));
        PdaSexLabel.SetMessage(PdaLine("passport-ui-sex", sexText));
        PdaBirthLabel.SetMessage(PdaLine("passport-ui-date-of-birth", Loc.GetString("passport-ui-year-value", ("year", yearOfBirth))));
        PdaHeightLabel.SetMessage(PdaLine("passport-ui-height", Loc.GetString("passport-ui-height-value", ("height", height))));
        PdaPidLabel.SetMessage(PdaLine("passport-ui-number", string.IsNullOrEmpty(pid) ? "-----" : pid));
        PdaAuthLabel.Text = Loc.GetString("passport-ui-pda-auth");
    }

    private static FormattedMessage PdaLine(string captionLoc, string value)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive($"[color=#3AA0A0]{FormattedMessage.EscapeText(Loc.GetString(captionLoc))}[/color]  ");
        msg.AddMarkupPermissive($"[color=#7CFFC8]{FormattedMessage.EscapeText(value)}[/color]");
        return msg;
    }

    private void SetPdaMode(bool pda)
    {
        PaperModeButton.Pressed = !pda;
        PdaModeButton.Pressed = pda;
        PaperRoot.Visible = !pda;
        PdaRoot.Visible = pda;
    }

    private void ApplyTheme(string? nationality)
    {
        var theme = GetTheme(nationality);

        CoverPanel.PanelOverride = Box(theme.Leather, theme.Gold, 3);
        PaperRoot.PanelOverride = Box(theme.Page, theme.Gold, 2);
        BannerPanel.PanelOverride = Box(theme.Leather);
        PhotoOuterFrame.PanelOverride = Box(Color.FromHex("#2A2118"), theme.Gold, 3);
        MrzPanel.PanelOverride = Box(Color.FromHex("#1F1812"));

        CountryLabel.FontColorOverride = theme.Gold;
        DocumentTitleLabel.FontColorOverride = theme.Page;
        PhotoCaptionLabel.FontColorOverride = PaperMuted;
        PhotoCodeLabel.FontColorOverride = PaperMuted;

        foreach (var label in new[]
                 {
                     TypeValueLabel, CodeValueLabel, NumberValueLabel, SurnameLabel, GivenNamesLabel,
                     NationalityLabel, SpeciesLabel, BirthLabel, SexLabel, HeightLabel, AuthorityLabel, MarksLabel
                 })
        {
            label.FontColorOverride = PaperInk;
        }

        PdaHeaderLabel.FontColorOverride = PdaGreen;
        PdaStatusLabel.FontColorOverride = PdaGreen;
        PdaAuthLabel.FontColorOverride = PdaGreen;
        PdaFooterLabel.FontColorOverride = Color.FromHex("#3AA0A0");
    }

    private void ReloadPhoto(HumanoidCharacterProfile profile)
    {
        DeletePhotoDummy();

        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return;

        var dummy = _entityManager.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);
        _entityManager.System<HumanoidAppearanceSystem>().LoadProfile(dummy, profile);
        _entityManager.System<MetaDataSystem>().SetEntityName(dummy, profile.Name);

        _photoDummy = dummy;
        PhotoView.SetEntity(dummy);
        PdaPhotoView.SetEntity(dummy);
        PhotoView.Modulate = new Color(1f, 0.96f, 0.9f);
    }

    private void DeletePhotoDummy()
    {
        if (_photoDummy == null)
            return;

        _entityManager.DeleteEntity(_photoDummy.Value);
        _photoDummy = null;
        PhotoView.SetEntity(null);
        PdaPhotoView.SetEntity(null);
    }

    private void BuildMrz(string code, string surname, string given, string pid, int yearOfBirth, Sex sex)
    {
        var sexChar = sex switch
        {
            Sex.Male => "M",
            Sex.Female => "F",
            _ => "X",
        };

        var line1 = PadMrz($"P<{SanitizeMrz(code)}<{SanitizeMrz(surname)}<<{SanitizeMrz(given)}", 44);
        var line2 = PadMrz($"{SanitizeMrz(pid.Replace("-", string.Empty))}{SanitizeMrz(code)}{yearOfBirth % 100:00}{sexChar}", 44);
        MrzLine1Label.Text = line1;
        MrzLine2Label.Text = line2;
    }

    private static string SanitizeMrz(string value)
    {
        var chars = new char[value.Length];
        var n = 0;
        foreach (var c in value.ToUpperInvariant())
        {
            if (char.IsLetterOrDigit(c))
                chars[n++] = c;
            else if (c is ' ' or '-')
                chars[n++] = '<';
        }

        return n == 0 ? string.Empty : new string(chars, 0, n);
    }

    private static string PadMrz(string value, int length)
    {
        if (value.Length >= length)
            return value[..length];

        return value.PadRight(length, '<');
    }

    private static (string Surname, string Given) SplitName(string name)
    {
        var parts = name.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return ("-----", "-----");
        if (parts.Length == 1)
            return (parts[0], parts[0]);

        return (parts[^1], string.Join(' ', parts[..^1]));
    }

    private string GetNationalityName(string nationality)
    {
        if (_prototypeManager.TryIndex<NationalityPrototype>(nationality, out var proto))
            return Loc.GetString(proto.NameKey);

        return nationality;
    }

    private static string GetNationalityCode(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => "TSF",
            "Imperial" => "IMP",
            "USSP" => "SSP",
            "FreeColonies" => "FCL",
            _ => "XXX",
        };
    }

    private string GetSpeciesName(string species)
    {
        if (_prototypeManager.TryIndex<SpeciesPrototype>(species, out var proto))
            return Loc.GetString(proto.Name);

        return species;
    }

    private static string LocSex(Sex sex)
    {
        return sex switch
        {
            Sex.Male => Loc.GetString("humanoid-profile-editor-sex-male-text"),
            Sex.Female => Loc.GetString("humanoid-profile-editor-sex-female-text"),
            _ => Loc.GetString("humanoid-profile-editor-sex-unsexed-text"),
        };
    }

    private int GetHeightCm(HumanoidCharacterProfile profile)
    {
        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return (int) MathF.Round(profile.Appearance.Height * 176.1f);

        return (int) MathF.Round(profile.Appearance.Height * species.AverageHeight);
    }

    private static PassportTheme GetTheme(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => new PassportTheme(
                Color.FromHex("#1B365D"),
                Color.FromHex("#C9A227"),
                Color.FromHex("#E7D7B6")),
            "Imperial" => new PassportTheme(
                Color.FromHex("#5C1212"),
                Color.FromHex("#D4AF37"),
                Color.FromHex("#F1DEC0")),
            "USSP" => new PassportTheme(
                Color.FromHex("#7A1616"),
                Color.FromHex("#FFD54A"),
                Color.FromHex("#F0D9B5")),
            "FreeColonies" => new PassportTheme(
                Color.FromHex("#1F4D3A"),
                Color.FromHex("#A8D5A2"),
                Color.FromHex("#E4EEDF")),
            _ => new PassportTheme(
                Color.FromHex("#3B1F1A"),
                Color.FromHex("#C9A227"),
                Color.FromHex("#E8D9B8")),
        };
    }

    private static StyleBoxFlat Box(Color background, Color? border = null, int thickness = 0)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border ?? background,
            BorderThickness = new Thickness(thickness),
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            DeletePhotoDummy();

        base.Dispose(disposing);
    }

    private readonly record struct PassportTheme(Color Leather, Color Gold, Color Page);
}
