- type: startingGear
  parent: USSPCommissarGear
  id: SpnCouncilMemberGear
  equipment:
    ears: ClothingHeadsetSpnCommand
    pocket1: WeaponRevolverMateba
    pocket2: SpeedLoader45_magnumFMJ
  storage:
    back:
    - RadioHandheldNF
    - SpnSecApartmentTablet

- type: startingGear
  parent: USSPSergeantGear
  id: SpnFleetOfficerGear
  equipment:
    ears: ClothingHeadsetSpnCommand

- type: startingGear
  id: SpnUnionDiplomatGear
  equipment:
    ears: ClothingHeadsetSpnCommand
    pocket1: WeaponRevolverFitz
    pocket2: SpeedLoader45_magnumFMJ
  storage:
    back:
    - RadioHandheldNF

- type: startingGear
  parent: USSPCorporalGear
  id: SpnSquadLeaderGear
  equipment:
    ears: ClothingHeadsetSpn

- type: startingGear
  parent: USSPMedicGear
  id: SpnCorpsmanGear
  equipment:
    ears: ClothingHeadsetSpn

- type: startingGear
  parent: USSPCorporalGear
  id: SpnSapperGear
  equipment:
    ears: ClothingHeadsetSpn

- type: startingGear
  parent: USSPRiflemanGear
  id: SpnRiflemanGear
  equipment:
    ears: ClothingHeadsetSpn

- type: startingGear
  parent: USSPRiflemanGear
  id: SpnTraineeGear
  equipment:
    ears: ClothingHeadsetSpn
