- type: loadout
  id: SpnBoxSurvivalNFOxygenExtended
  name: extended-oxygen survival box
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: OxygenBreatherNF
  storage:
    back:
    - SpnBoxSurvivalMonoOxygenExtended

- type: loadout
  id: SpnBoxSurvivalNFNitrogenExtended
  name: extended-nitrogen survival box
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: NitrogenBreatherNF
  storage:
    back:
    - SpnBoxSurvivalMonoNitrogenExtended
