- type: job
  id: SpnTrainee
  name: forge-job-name-spn-trainee
  description: forge-job-desc-spn-trainee
  playTimeTracker: JobSpnTrainee
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600
  startingGear: SpnTraineeGear
  alwaysUseSpawner: true
  setPreference: true
  icon: JobIconSpnTrainee
  supervisors: job-supervisors-spn-fleet-officer
  canBeAntag: false
  weight: 50
  displayWeight: 25
  assignedCompany: SPN
  assignedNationality: USSP
  special:
  - !type:AddImplantSpecial
    implants: [ SpnMindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovaCygniBasic
    languagesUnderstood:
    - NovaCygniBasic
  accessGroups:
  - GeneralAccess
  - USSPLow
