using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BsEnergy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Forge.BsEnergy;

[GenerateTypedNameReferences]
public sealed partial class BsReceiverAuthenticationWindow : FancyWindow
{
    private const int PasswordMaxLenght = BsEnergySettings.PasswordMaxLenght;
    private readonly TimeSpan _closeDelay = TimeSpan.FromSeconds(0.5f);
    private readonly string _connectingResultTrue = Loc.GetString("ui-bs-authentication-connecting-result-true");
    private readonly string _connectingResultFalse = Loc.GetString("ui-bs-authentication-connecting-result-false");
    private NetEntity _transmitterToConnect = NetEntity.Invalid;
    private int _nextRequestId = 1;
    private int _lastRequestId;
    private bool _responseReceived;

    public event Action<NetEntity, string, int>? OnPasswordEntered;

    public BsReceiverAuthenticationWindow()
    {
        RobustXamlLoader.Load(this);

        PasswordLineEdit.IsValid = text => text.Length <= PasswordMaxLenght;
        PasswordLineEdit.OnTextEntered += args =>
        {
            var requestId = _nextRequestId++;
            _lastRequestId = requestId;
            _responseReceived = false;
            OnPasswordEntered?.Invoke(_transmitterToConnect, args.Text, requestId);
        };
        PasswordLineEdit.OnTextChanged += args =>
        {
            ConnectingResult.Visible = false;

            if (args.Text.Length > PasswordMaxLenght)
                PasswordLineEdit.SetText(args.Text[..PasswordMaxLenght]);
        };
    }

    public void UpdateUI(BsReceiverAuthenticationInterfaceStateMessage stateMessage)
    {
        _transmitterToConnect = stateMessage.Transmitter;
        ConnectionTo.Text = $"{stateMessage.TransmitterGridName}";

        if (!stateMessage.IsResponse || stateMessage.RequestId != _lastRequestId || _responseReceived)
            return;

        _responseReceived = true;
        ConnectingResult.Text = stateMessage.ConnectingResult ? _connectingResultTrue : _connectingResultFalse;
        ConnectingResult.Modulate = stateMessage.ConnectingResult ? Color.Lime : Color.Red;
        ConnectingResult.Visible = true;

        if (stateMessage.ConnectingResult)
        {
            Timer.Spawn(_closeDelay,
                () =>
                {
                    if (IsOpen)
                        Close();
                });
        }
    }
}
