using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BsEnergy;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.BsEnergy;

[GenerateTypedNameReferences]
public sealed partial class BsTransmitterWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly string _minuteLocStr = Loc.GetString("ui-bs-energy-time-minute");
    private readonly string _balanceLocStr = Loc.GetString("ui-bs-transmitter-money-label");
    private const int PasswordMaxLenght = BsEnergySettings.PasswordMaxLenght;
    private int _maxValue;
    private int _stepSize;
    private int _power;

    public event Action<int>? OnChangeTargetPower;
    public event Action<int>? OnPriceChanged;
    public event Action<int>? OnConnectedDevicesChanged;
    public event Action<BaseButton.ButtonEventArgs>? OnEnableToggle;
    public event Action? OnWithdraw;
    public event Action<NetEntity>? OnKick;
    public event Action<string>? OnPasswordChanged;

    private readonly Dictionary<NetEntity, ReceiversUiElements> _currentReceiversUiElements = new();
    private readonly Dictionary<NetEntity, HistoryUiElements> _historyUiElements = new();

    private readonly StyleBoxFlat _styleBoxFlat = new()
    {
        BorderThickness = new(2),
        BorderColor = Color.FromHex("#333333"),
        BackgroundColor = Color.FromHex("#181818"),
    };

    private sealed class HistoryUiElements
    {
        public RichTextLabel? GridName;
        public RichTextLabel? TotalEnergyReceived;
        public RichTextLabel? TotalMoneyTransferred;
    }

    private sealed class ReceiversUiElements
    {
        public Container? Container;
        public RichTextLabel? GridName;
        public RichTextLabel? RequestedPower;
        public RichTextLabel? ReceivedPower;
        public RichTextLabel? TotalEnergyReceived;
        public RichTextLabel? TotalMoneyTransferred;
        public int Priority;
    }

    public BsTransmitterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CurrentSupplyLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        PowerConsumerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        TargetPowerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-unanchored");
        ExpectedIncomeLabel.Text = $"$0 / {_minuteLocStr}";

        PriceSpinBox.IsValid = val => val >= 0;
        PriceSpinBox.LineEditControl.PlaceHolder = $"{BsEnergySettings.PassiveIncome}";

        PasswordLineEdit.IsValid = text => text.Length <= PasswordMaxLenght;

        Tab.SetTabTitle(0, Loc.GetString("ui-bs-transmitter-settings-tab"));
        Tab.SetTabTitle(1, Loc.GetString("ui-bs-transmitter-receivers-tab"));
        Tab.SetTabTitle(2, Loc.GetString("ui-bs-transmitter-history-tab"));

        EnableButton.OnPressed += args => OnEnableToggle?.Invoke(args);
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke();
        PriceSpinBox.ValueChanged += args => OnPriceChanged?.Invoke(args.Value);
        ConnectedDevicesSpinBox.ValueChanged += args => OnConnectedDevicesChanged?.Invoke(args.Value);
        PasswordLineEdit.OnTextChanged += args =>
        {
            var newText = args.Text;
            if (newText.Length > PasswordMaxLenght)
            {
                newText = newText[..PasswordMaxLenght];
                PasswordLineEdit.SetText(newText);
            }

            OnPasswordChanged?.Invoke(newText);
        };
    }

    public void SetEntity(EntityUid uid)
    {
        SpriteViewControl.SetEntity(uid);
    }

    public void UpdateUI(BsTransmitterInterfaceStateMessage stateMessage)
    {
        if (_maxValue == 0 && stateMessage.MaxValue > 0)
            _maxValue = stateMessage.MaxValue;

        if (_stepSize == 0 && stateMessage.MaxValue > 0)
        {
            _stepSize = stateMessage.StepSize;
            RequestedPowerIncreaseButton.Text = Loc.GetString("ui-bs-energy-step-increase", ("watts", _stepSize));
            RequestedPowerDecreaseButton.Text = Loc.GetString("ui-bs-energy-step-decrease", ("watts", _stepSize));

            ConnectedDevicesSpinBox.IsValid = val => val >= 0 && val <= stateMessage.MaxConnected;
            ConnectedDevicesSpinBox.LineEditControl.PlaceHolder = $"{stateMessage.MaxConnected}";

            RequestedPowerIncreaseButton.OnPressed += _ => RequestedPowerChanged(_stepSize);
            RequestedPowerDecreaseButton.OnPressed += _ => RequestedPowerChanged(-1 * _stepSize);
        }

        _power = stateMessage.TargetPower;
        EnableButton.Pressed = stateMessage.Enabled;
        ExpectedIncomeLabel.Text = $"${stateMessage.Income:F0} / {_minuteLocStr}";
        ConnectedDevicesLabel.Text = $"{stateMessage.ConnectedCount} / ";
        TotalMoneyLabel.Text = $"{_balanceLocStr} ${stateMessage.Money:F0}";
        PowerConsumerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.PowerConsumer));
        TargetPowerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.TargetPower));
        CurrentSupplyLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.AvailablePower));

        RequestedPowerDecreaseButton.Disabled = stateMessage.TargetPower <= 0;
        RequestedPowerIncreaseButton.Disabled = stateMessage.TargetPower >= _maxValue;

        if (stateMessage.NetworkStats is { } netStats)
        {
            NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-network-stats-value", ("load", netStats.Load), ("supply", netStats.Supply));

            var good = netStats.Load <= netStats.Supply;
            NetworkStatsLabel.SetOnlyStyleClass(good ? "Good" : "Caution");
        }
        else
        {
            NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-unanchored");
            NetworkStatsLabel.StyleClasses.Clear();
        }

        if (!PriceSpinBox.LineEditControl.HasKeyboardFocus())
            PriceSpinBox.OverrideValue(stateMessage.Price);

        if (!ConnectedDevicesSpinBox.LineEditControl.HasKeyboardFocus())
            ConnectedDevicesSpinBox.OverrideValue(stateMessage.ConnectingLimit);

        if (!PasswordLineEdit.HasKeyboardFocus())
            PasswordLineEdit.Text = stateMessage.Password;

        UpdateReceiversUI(stateMessage.ReceiversData, stateMessage.HistoryData);
        UpdateHistoryUI(stateMessage.HistoryData);
    }

    private void UpdateHistoryUI(Dictionary<NetEntity, UpdateHistoryData> historyData)
    {
        ulong sumTotalMoneyTransferred = 0;
        ulong sumTotalEnergyReceived = 0;

        foreach (var (key, value) in historyData)
        {
            sumTotalMoneyTransferred += value.TotalMoneyTransferred;
            sumTotalEnergyReceived += value.TotalEnergyReceived;

            if (_historyUiElements.TryGetValue(key, out var elements))
            {
                elements.GridName?.Text = value.GridReceiverName;
                elements.TotalMoneyTransferred?.Text = $"{Loc.GetString("ui-bs-transmitter-total-money-received-label")} ${value.TotalMoneyTransferred}";
                elements.TotalEnergyReceived?.Text = $"{Loc.GetString("ui-bs-transmitter-total-energy-received-label")} {Loc.GetString("ui-bs-energy-network-hours-value", ("watts", value.TotalEnergyReceived))}";
            }
            else
            {
                var panelContainer = new PanelContainer { HorizontalExpand = true, PanelOverride = _styleBoxFlat};
                var mainHorizontalBoxInPanel = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
                var verticalBoxInPanel = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };

                var gridName = new RichTextLabel { Text = $"{value.GridReceiverName}", HorizontalExpand = true};
                var totalMoneyTransferred = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-total-money-received-label")} ${value.TotalMoneyTransferred}", HorizontalAlignment = HAlignment.Left, HorizontalExpand = true };
                var totalEnergyReceived = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-total-energy-received-label")} {Loc.GetString("ui-bs-energy-network-hours-value", ("watts", value.TotalEnergyReceived))}", HorizontalAlignment = HAlignment.Right, HorizontalExpand = true };

                mainHorizontalBoxInPanel.AddChild(totalMoneyTransferred);
                mainHorizontalBoxInPanel.AddChild(totalEnergyReceived);

                verticalBoxInPanel.AddChild(gridName);
                verticalBoxInPanel.AddChild(mainHorizontalBoxInPanel);

                panelContainer.AddChild(verticalBoxInPanel);

                HistoryBoxContainer.AddChild(panelContainer);

                var newElements = new HistoryUiElements
                {
                    GridName = gridName,
                    TotalMoneyTransferred = totalMoneyTransferred,
                    TotalEnergyReceived = totalEnergyReceived,
                };

                _historyUiElements[key] = newElements;
            }
        }

        HistoryTotalMoneyLabel.Text = $"{Loc.GetString("ui-bs-transmitter-history-total-money-transfer-label")} ${sumTotalMoneyTransferred}";
        HistoryTotalEnergyReceivedLabel.Text = $"{Loc.GetString("ui-bs-transmitter-history-total-energy-received-label")} {Loc.GetString("ui-bs-energy-network-hours-value", ("watts", sumTotalEnergyReceived))}";
    }

    private void UpdateReceiversUI(Dictionary<NetEntity, UpdateReceiversData> receiversData, Dictionary<NetEntity, UpdateHistoryData> historyData)
    {
        CheckingRemoveReceivers(receiversData);

        foreach (var (key, value) in receiversData)
        {
            if (!historyData.TryGetValue(key, out var history))
                history = new();

            var requestedPowerTextValue = float.IsInfinity(value.RequestedPower) ? $"{value.RequestedPower}" : Loc.GetString("ui-bs-energy-network-value", ("watts", value.RequestedPower));

            if (_currentReceiversUiElements.TryGetValue(key, out var elements))
            {

                elements.GridName?.Text = value.GridReceiverName;
                elements.RequestedPower?.Text = $"{Loc.GetString("ui-bs-transmitter-requested-power-label")} {requestedPowerTextValue}";
                elements.ReceivedPower?.Text = $"{Loc.GetString("ui-bs-transmitter-received-power-label")} {Loc.GetString("ui-bs-energy-network-value", ("watts", value.ReceivedPower))}";
                elements.TotalMoneyTransferred?.Text = $"{Loc.GetString("ui-bs-transmitter-total-money-received-label")} ${history.TotalMoneyTransferred}";
                elements.TotalEnergyReceived?.Text = $"{Loc.GetString("ui-bs-transmitter-total-energy-received-label")} {Loc.GetString("ui-bs-energy-network-hours-value", ("watts", history.TotalEnergyReceived))}";
                elements.Priority = value.Priority;
            }
            else
            {
                var panelContainer = new PanelContainer { HorizontalExpand = true, PanelOverride = _styleBoxFlat};
                var mainHorizontalBoxInPanel = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
                var verticalBoxInPanel = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
                var hPowerBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
                var hTotalBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };

                var gridName = new RichTextLabel { Text = $"{value.GridReceiverName}", HorizontalExpand = true};
                var requestedPower = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-requested-power-label")} {requestedPowerTextValue}", HorizontalAlignment = HAlignment.Left, HorizontalExpand = true};
                var receivedPower = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-received-power-label")} {Loc.GetString("ui-bs-energy-network-value", ("watts", value.ReceivedPower))}", HorizontalAlignment = HAlignment.Right, HorizontalExpand = true};
                var totalMoneyTransferred = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-total-money-received-label")} ${history.TotalMoneyTransferred}", HorizontalAlignment = HAlignment.Left, HorizontalExpand = true};
                var totalEnergyReceived = new RichTextLabel { Text = $"{Loc.GetString("ui-bs-transmitter-total-energy-received-label")} {Loc.GetString("ui-bs-energy-network-hours-value", ("watts", history.TotalEnergyReceived))}", HorizontalAlignment = HAlignment.Right, HorizontalExpand = true};
                var disconnectButton = new TextureButton { HorizontalAlignment = HAlignment.Right, StyleClasses = { "windowCloseButton" }, Scale = new (2, 1), Margin = new(20, 0, 0, 0)};

                disconnectButton.OnPressed += _ => OnKick?.Invoke(key);
                disconnectButton.Visible = key.IsValid();

                hPowerBox.AddChild(requestedPower);
                hPowerBox.AddChild(receivedPower);

                hTotalBox.AddChild(totalMoneyTransferred);
                hTotalBox.AddChild(totalEnergyReceived);

                verticalBoxInPanel.AddChild(gridName);
                verticalBoxInPanel.AddChild(hPowerBox);
                verticalBoxInPanel.AddChild(hTotalBox);

                mainHorizontalBoxInPanel.AddChild(verticalBoxInPanel);
                mainHorizontalBoxInPanel.AddChild(disconnectButton);

                panelContainer.AddChild(mainHorizontalBoxInPanel);

                ReceiversBoxContainer.AddChild(panelContainer);

                var newElements = new ReceiversUiElements
                {
                    Container = panelContainer,
                    GridName = gridName,
                    RequestedPower = requestedPower,
                    ReceivedPower = receivedPower,
                    TotalMoneyTransferred = totalMoneyTransferred,
                    TotalEnergyReceived = totalEnergyReceived,
                    Priority = value.Priority,
                };

                _currentReceiversUiElements[key] = newElements;
            }
        }

        SortReceiversByPriority();
    }

    private void SortReceiversByPriority()
    {
        var isAlreadySorted = true;
        var ordered = _currentReceiversUiElements
            .OrderBy(pair => pair.Value.Priority)
            .ThenBy(pair => pair.Key)
            .ToList();

        var index = 0;
        foreach (var child in ReceiversBoxContainer.Children)
        {
            if (index >= ordered.Count)
            {
                isAlreadySorted = false;
                break;
            }

            var expectedContainer = ordered[index].Value.Container;
            if (!ReferenceEquals(child, expectedContainer))
            {
                isAlreadySorted = false;
                break;
            }

            index++;
        }

        if (index != ordered.Count)
            isAlreadySorted = false;

        if (isAlreadySorted)
            return;

        foreach (var (_, elements) in ordered)
        {
            var container = elements.Container;
            if (container == null || container.Disposed)
                continue;

            container.Orphan();
            ReceiversBoxContainer.AddChild(container);
        }
    }

    private void CheckingRemoveReceivers(Dictionary<NetEntity, UpdateReceiversData> newData)
    {
        var toRemove = _currentReceiversUiElements.Keys.Where(key => !newData.ContainsKey(key)).ToList();
        foreach (var key in toRemove)
        {
            if (!_currentReceiversUiElements.TryGetValue(key, out var elements))
                continue;

            elements.Container?.Dispose();
            _currentReceiversUiElements.Remove(key);
        }
    }

    private void RequestedPowerChanged(int watts)
    {
        if (_maxValue == 0)
            return;

        var newVal = _power + watts;
        _power = newVal < _maxValue ? Math.Max(0, newVal) : _maxValue;
        OnChangeTargetPower?.Invoke(_power);
    }
}
