using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Warehouse;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Warehouse.UI;

[GenerateTypedNameReferences]
public sealed partial class WarehouseSiloMenu : FancyWindow
{
    public event Action<string>? OnWithdraw;

    public WarehouseSiloMenu()
    {
        RobustXamlLoader.Load(this);
        EntryList.OnItemSelected += args =>
        {
            if (EntryList[args.ItemIndex].Metadata is string stackType)
                OnWithdraw?.Invoke(stackType);
        };
    }

    public void Update(WarehouseSiloBuiState state)
    {
        EntryList.Clear();
        if (state.Entries.Count == 0)
        {
            EntryList.Add(new ItemList.Item(EntryList)
            {
                Text = Loc.GetString("warehouse-silo-ui-empty"),
                Selectable = false,
            });
            return;
        }

        foreach (var entry in state.Entries)
        {
            EntryList.Add(new ItemList.Item(EntryList)
            {
                Text = Loc.GetString("warehouse-silo-ui-entry", ("name", entry.Name), ("count", entry.Count)),
                Metadata = entry.StackType,
            });
        }
    }
}
