- type: job
  id: Praetorian
  name: forge-job-name-praetorian
  description: forge-job-desc-praetorian
  playTimeTracker: JobPraetorianGuard
  supervisors: job-supervisors-praefect
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 129600 # 36 hours
    - !type:DepartmentTimeRequirement
      department: Empire
      time: 108000 # 30 hours
    - !type:RoleTimeRequirement
      role: JobArbiter
      time: 21600 # 6 hours
    - !type:RoleTimeRequirement
      role: JobCardinal
      time: 21600 # 6 hours
    - !type:SpeciesRequirement
      species:
        - Human
    - !type:AgeRequirement
      requiredAge: 40
    - !type:SexRequirement
      sex:
      - Male
  whitelisted: true
  startingGear: PraetorianGear
  alwaysUseSpawner: true
  icon: JobIconPraetorian
  assignedCompany: Imperial
  assignedNationality: Imperial
  weight: 25
  displayWeight: 25
  canBeAntag: false
  setPreference: true
  access:
  - EmpireInqusitor
  - EmpireSmallInq
  accessGroups:
  - CommandEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire
  - !type:AddImplantSpecial
    implants: [ ImplantGuard , EmpireTrackingImplant ]

- type: startingGear
  id: PraetorianGear
  storage:
    back:
    - PinpointerUniversal
