using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class JobPresetListItem : Button
{
    public sealed class ViewState(string title, string subtitle, Texture? iconTexture)
    {
        public string Title { get; } = title;
        public string Subtitle { get; } = subtitle;
        public Texture? IconTexture { get; } = iconTexture;
    }

    public JobPresetListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);

        JobTitle.Text = state.Title;
        JobSubtitle.SetMessage(state.Subtitle);
        JobIcon.Texture = state.IconTexture;
    }

    public void SetSubtitle(string text, Color color)
    {
        JobSubtitle.SetMessage(text);
        JobSubtitle.Modulate = color;
    }
}
