using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

// Forge-Change-full: company whitelist + owners
namespace Content.Client._DV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanyWhitelistPanel : PanelContainer
{
    public Action<string, bool>? OnSetCompany;
    public Action<string, bool>? OnSetOwner;

    public CompanyWhitelistPanel(
        List<string> companies,
        string title,
        Color color,
        IPrototypeManager proto,
        HashSet<string> whitelists,
        HashSet<string> owners)
    {
        RobustXamlLoader.Load(this);

        var allWhitelisted = true;
        foreach (var id in companies)
        {
            if (!proto.TryIndex<CompanyPrototype>(id, out var company))
                continue;

            var thisCompany = id;
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var memberBox = new CheckBox
            {
                Text = company.Name,
                Pressed = whitelists.Contains(id),
                MinWidth = 180,
            };
            memberBox.OnPressed += _ => OnSetCompany?.Invoke(thisCompany, memberBox.Pressed);

            var ownerBox = new CheckBox
            {
                Text = Loc.GetString("company-admin-owner"),
                Pressed = owners.Contains(id),
                Disabled = !memberBox.Pressed,
                ToolTip = Loc.GetString("company-admin-owner-tooltip"),
            };
            ownerBox.OnPressed += _ => OnSetOwner?.Invoke(thisCompany, ownerBox.Pressed);

            memberBox.OnPressed += _ =>
            {
                ownerBox.Disabled = !memberBox.Pressed;
                if (!memberBox.Pressed && ownerBox.Pressed)
                {
                    ownerBox.Pressed = false;
                    OnSetOwner?.Invoke(thisCompany, false);
                }
            };

            row.AddChild(memberBox);
            row.AddChild(ownerBox);
            CompaniesContainer.AddChild(row);

            allWhitelisted &= memberBox.Pressed;
        }

        CompaniesSet.Text = title;
        CompaniesSet.Modulate = color;
        CompaniesSet.Pressed = allWhitelisted;
        CompaniesSet.OnPressed += _ => OnSetPressed(companies, whitelists);
    }

    private void OnSetPressed(List<string> companies, HashSet<string> whitelists)
    {
        foreach (var id in companies)
        {
            if (whitelists.Contains(id) != CompaniesSet.Pressed)
                OnSetCompany?.Invoke(id, CompaniesSet.Pressed);
        }
    }
}
