using System.Linq;
using System.Numerics;
using Content.Shared._Forge;
using Content.Shared._Forge.Company;
using Content.Shared._Forge.Sponsor;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Forge.Company;

[GenerateTypedNameReferences]
public sealed partial class CompanyManagementUiFragment : BoxContainer
{
    public Action<CompanyManagementUiMessageEvent>? OnMessage;

    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprite;
    private readonly IConfigurationManager _cfg;
    private readonly ISharedSponsorManager _sponsors;
    private readonly IPlayerManager _players;
    private readonly CompanyManagementStyles _styles;

    private readonly List<string> _paletteIds = new();
    private bool _suppressPaletteEvents;
    private bool _previewOpen;
    private CompanyUiPalettePrototype? _previewPalette;

    private readonly BoxContainer _infoTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _bankTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _relationsTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _rosterTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _logsTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _invitesTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };
    private readonly BoxContainer _rolesTab = new() { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };

    private CompanyManagementUiState? _state;
    private bool _editingBulletin;

    private static readonly CompanyPermission[] EditablePermissions =
    {
        CompanyPermission.EditBulletin,
        CompanyPermission.Invite,
        CompanyPermission.Kick,
        CompanyPermission.ManageRoles,
        CompanyPermission.AssignAccess,
        CompanyPermission.BankDeposit,
        CompanyPermission.BankWithdraw,
        CompanyPermission.DeclareWar,
        CompanyPermission.DeclareAlliance,
        CompanyPermission.ViewLogs,
        CompanyPermission.ConfigureDoors,
    };

    public CompanyManagementUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _sprite = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        _cfg = IoCManager.Resolve<IConfigurationManager>();
        _sponsors = IoCManager.Resolve<ISharedSponsorManager>();
        _players = IoCManager.Resolve<IPlayerManager>();

        var initialPalette = ResolvePalette(_cfg.GetCVar(ForgeVars.CompanyUiPalette));
        _styles = new CompanyManagementStyles(
            IoCManager.Resolve<IResourceCache>(),
            IoCManager.Resolve<IUserInterfaceManager>(),
            initialPalette);

        Orientation = LayoutOrientation.Vertical;
        Stylesheet = _styles.CreateFragmentStylesheet();
        ApplyChrome();
        SetupPalettePicker();
        SetupPaletteMockup();
        UpdatePalettePreview(initialPalette);

        Tabs.AddChild(WrapScroll(_infoTab));
        Tabs.AddChild(WrapScroll(_bankTab));
        Tabs.AddChild(WrapScroll(_relationsTab));
        Tabs.AddChild(WrapScroll(_rosterTab));
        Tabs.AddChild(WrapScroll(_logsTab));
        Tabs.AddChild(WrapScroll(_invitesTab));
        Tabs.AddChild(WrapScroll(_rolesTab));

        Tabs.SetTabTitle(0, Loc.GetString("company-pda-tab-info"));
        Tabs.SetTabTitle(1, Loc.GetString("company-pda-tab-bank"));
        Tabs.SetTabTitle(2, Loc.GetString("company-pda-tab-relations"));
        Tabs.SetTabTitle(3, Loc.GetString("company-pda-tab-roster"));
        Tabs.SetTabTitle(4, Loc.GetString("company-pda-tab-logs"));
        Tabs.SetTabTitle(5, Loc.GetString("company-pda-tab-invites"));
        Tabs.SetTabTitle(6, Loc.GetString("company-pda-tab-roles"));

        Tabs.TabFontColorOverride = _styles.Theme.TabActive;
        Tabs.TabFontColorInactiveOverride = _styles.Theme.TabInactive;
    }

    private bool IsSponsor()
    {
        var user = _players.LocalSession?.UserId;
        return user != null && _sponsors.TryGetSponsor(user.Value, out var level) && level != SponsorLevel.None;
    }

    private CompanyUiPalettePrototype ResolvePalette(string? id)
    {
        if (!string.IsNullOrWhiteSpace(id) &&
            _proto.TryIndex<CompanyUiPalettePrototype>(id, out var palette))
        {
            if (!palette.RequiresSponsor || IsSponsor())
                return palette;
        }

        var fallback = _proto.Index<CompanyUiPalettePrototype>(CompanyManagementStyles.DefaultPaletteId);
        if (_cfg.GetCVar(ForgeVars.CompanyUiPalette) != fallback.ID)
            _cfg.SetCVar(ForgeVars.CompanyUiPalette, fallback.ID);
        return fallback;
    }

    private void SetupPaletteMockup()
    {
        PalettePreviewToggle.Text = Loc.GetString("company-ui-palette-preview-button");
        PalettePreviewToggle.ToolTip = Loc.GetString("company-ui-palette-preview-button-tooltip");
        PalettePreviewToggle.AddStyleClass(Content.Client._Wega.Stylesheets.SecApartmentStyles.StyleClassButtonRed);
        PalettePreviewToggle.OnPressed += _ =>
        {
            _previewOpen = !_previewOpen;
            PaletteMockupOuter.Visible = _previewOpen;
            PalettePreviewToggle.Text = _previewOpen
                ? Loc.GetString("company-ui-palette-preview-hide")
                : Loc.GetString("company-ui-palette-preview-button");
        };

        PaletteMockupCaption.Text = Loc.GetString("company-ui-palette-preview-caption");
        PaletteMockupTabActiveLabel.Text = Loc.GetString("company-pda-tab-info");
        PaletteMockupTabIdleLabel.Text = Loc.GetString("company-pda-tab-bank");
        PaletteMockupCardHeading.Text = Loc.GetString("company-ui-palette-preview-sample-heading");
        PaletteMockupCardText.Text = Loc.GetString("company-ui-palette-preview-sample-text");
        PaletteMockupButtonLabel.Text = Loc.GetString("company-pda-save");
        PaletteMockupTitle.Text = "PLXCOR";
        PaletteMockupMeta.Text = Loc.GetString("company-ui-palette-preview-sample-meta");
    }

    private void UpdatePalettePreview(CompanyUiPalettePrototype palette)
    {
        _previewPalette = palette;
        var name = Loc.GetString(palette.Name);
        var locked = palette.RequiresSponsor && !IsSponsor();

        PaletteMockupCaption.Text = locked
            ? Loc.GetString("company-ui-palette-preview-locked", ("name", name))
            : Loc.GetString("company-ui-palette-preview-tooltip", ("name", name));

        // Paint the mini menu mockup with this palette so you see the overall look.
        PaletteMockupOuter.PanelOverride = _styles.MakePanelBox(palette.CreateSquadPanelBackground, palette.CreateSquadPanelBorder, 2, new Thickness(4));
        PaletteMockupFrame.PanelOverride = _styles.MakePanelBox(palette.ContentBackground, palette.ContentBorder, 2, new Thickness(2));
        PaletteMockupDivider.PanelOverride = _styles.MakePanelBox(palette.Divider, palette.Divider, 0, new Thickness(0));
        PaletteMockupTabActive.PanelOverride = _styles.MakePanelBox(palette.TabActiveBackground, palette.TabActive, 2, new Thickness(0));
        PaletteMockupTabIdle.PanelOverride = _styles.MakePanelBox(palette.TabInactiveBackground, palette.TabInactive, 2, new Thickness(0));
        PaletteMockupCard.PanelOverride = _styles.MakePanelBox(palette.CardBackground, palette.CardBorder, 2, new Thickness(0));
        PaletteMockupButton.PanelOverride = _styles.MakePanelBox(palette.ButtonBackground, palette.ButtonBorder, 1, new Thickness(0));

        PaletteMockupTitle.FontColorOverride = palette.Heading;
        PaletteMockupMeta.FontColorOverride = palette.SubText;
        PaletteMockupCaption.FontColorOverride = palette.SubText;
        PaletteMockupTabActiveLabel.FontColorOverride = palette.TabActive;
        PaletteMockupTabIdleLabel.FontColorOverride = palette.TabInactive;
        PaletteMockupCardHeading.FontColorOverride = palette.Heading;
        PaletteMockupCardText.FontColorOverride = palette.Text;
        PaletteMockupButtonLabel.FontColorOverride = palette.TabActive;

        // Auto-open mockup when browsing a locked sponsor palette.
        if (locked && !_previewOpen)
        {
            _previewOpen = true;
            PaletteMockupOuter.Visible = true;
            PalettePreviewToggle.Text = Loc.GetString("company-ui-palette-preview-hide");
        }
    }

    private void SetupPalettePicker()
    {
        PaletteOption.ToolTip = Loc.GetString("company-ui-palette-tooltip");
        _styles.StyleOption(PaletteOption);

        _suppressPaletteEvents = true;
        PaletteOption.Clear();
        _paletteIds.Clear();

        var selectedId = ResolvePalette(_cfg.GetCVar(ForgeVars.CompanyUiPalette)).ID;
        var selectedIndex = 0;
        var i = 0;
        foreach (var palette in _proto.EnumeratePrototypes<CompanyUiPalettePrototype>().OrderBy(p => p.RequiresSponsor).ThenBy(p => p.ID))
        {
            var label = Loc.GetString(palette.Name);
            if (palette.RequiresSponsor)
                label = Loc.GetString("company-ui-palette-sponsor-suffix", ("name", label));

            PaletteOption.AddItem(label, i);
            _paletteIds.Add(palette.ID);
            if (palette.ID == selectedId)
                selectedIndex = i;
            i++;
        }

        PaletteOption.SelectId(selectedIndex);
        _suppressPaletteEvents = false;

        PaletteOption.OnItemSelected += args =>
        {
            PaletteOption.SelectId(args.Id);
            if (_suppressPaletteEvents)
                return;
            if (args.Id < 0 || args.Id >= _paletteIds.Count)
                return;

            var id = _paletteIds[args.Id];
            if (!_proto.TryIndex<CompanyUiPalettePrototype>(id, out var palette))
                return;

            UpdatePalettePreview(palette);

            if (palette.RequiresSponsor && !IsSponsor())
            {
                PaletteOption.ToolTip = Loc.GetString("company-ui-palette-sponsor-required");
                return;
            }

            PaletteOption.ToolTip = Loc.GetString("company-ui-palette-tooltip");
            _cfg.SetCVar(ForgeVars.CompanyUiPalette, id);
            ApplyPalette(palette);
        };
    }

    private void ApplyPalette(CompanyUiPalettePrototype palette)
    {
        _styles.SetPalette(palette);
        Stylesheet = _styles.CreateFragmentStylesheet();
        ApplyChrome();
        UpdatePalettePreview(palette);
        Tabs.TabFontColorOverride = palette.TabActive;
        Tabs.TabFontColorInactiveOverride = palette.TabInactive;

        if (_state != null)
        {
            var keepBulletin = _editingBulletin;
            UpdateState(_state);
            _ = keepBulletin;
        }
    }

    private void ApplyChrome()
    {
        var theme = _styles.Theme;
        ContentBorder.ModulateSelfOverride = theme.ContentBorder;
        ContentBackground.ModulateSelfOverride = theme.ContentBackground;
        MainDivider.PanelOverride = _styles.MakePanelBox(theme.Divider, theme.Divider, 0, new Thickness(0));
        _styles.TintLabel(HeaderLabel, heading: true);
        _styles.TintLabel(StatusLabel);
        _styles.StyleOption(PaletteOption);
        PalettePreviewToggle.AddStyleClass(Content.Client._Wega.Stylesheets.SecApartmentStyles.StyleClassButtonRed);
        if (_previewPalette != null)
            UpdatePalettePreview(_previewPalette);
    }

    private static ScrollContainer WrapScroll(Control child)
    {
        var scroll = new ScrollContainer { VerticalExpand = true, HScrollEnabled = false };
        scroll.AddChild(child);
        return scroll;
    }

    public void UpdateState(CompanyManagementUiState state)
    {
        _editingBulletin = false;
        _state = state;

        HeaderLabel.Text = state.HasCompany
            ? state.CompanyName
            : Loc.GetString("company-pda-no-company");

        StatusLabel.Text = state.HasCompany
            ? Loc.GetString("company-pda-status",
                ("leader", string.IsNullOrWhiteSpace(state.LeaderName)
                    ? Loc.GetString("company-pda-leader-none")
                    : state.LeaderName),
                ("tier", Loc.GetString($"company-pda-access-{state.AccessTier.ToString().ToLowerInvariant()}")))
            : Loc.GetString("company-pda-invites-only");

        RebuildInfo();
        RebuildBank();
        RebuildRelations();
        RebuildRoster();
        RebuildLogs();
        RebuildInvites();
        RebuildRoles();
    }

    private void RebuildInfo()
    {
        _infoTab.RemoveAllChildren();
        if (_state is not { } state)
            return;

        if (!state.HasCompany)
        {
            _infoTab.AddChild(_styles.MakeListPanel(_styles.MakeText(Loc.GetString("company-pda-invites-only")), verticalExpand: false));
            return;
        }

        var stats = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 3 };
        stats.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-info-company", ("company", state.CompanyName))));
        stats.AddChild(_styles.MakeText(Loc.GetString("company-pda-info-leader", ("leader", state.LeaderName))));
        stats.AddChild(_styles.MakeText(Loc.GetString("company-pda-info-members", ("count", state.MemberCount))));
        stats.AddChild(_styles.MakeText(Loc.GetString("company-pda-info-access",
            ("tier", Loc.GetString($"company-pda-access-{state.AccessTier.ToString().ToLowerInvariant()}")))));
        _infoTab.AddChild(_styles.MakeCard(stats));

        var bulletinHeader = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4) };
        bulletinHeader.AddChild(_styles.MakeHeading(Loc.GetString("company-pda-bulletin")));
        _infoTab.AddChild(bulletinHeader);

        var canEdit = state.IsOwner || (state.Permissions & CompanyPermission.EditBulletin) != 0;
        var bulletinText = string.IsNullOrWhiteSpace(state.Bulletin)
            ? Loc.GetString("company-pda-bulletin-empty")
            : state.Bulletin;

        if (_editingBulletin && canEdit)
        {
            var edit = _styles.MakeLineEdit(text: state.Bulletin ?? string.Empty);
            edit.MinHeight = 72;
            var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 6 };
            body.AddChild(edit);

            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
            var save = _styles.MakeButton(Loc.GetString("company-pda-save"));
            save.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.SetBulletin,
                Text = edit.Text,
            });
            var cancel = _styles.MakeButton(Loc.GetString("company-pda-cancel"));
            cancel.OnPressed += _ =>
            {
                _editingBulletin = false;
                RebuildInfo();
            };
            row.AddChild(save);
            row.AddChild(cancel);
            body.AddChild(row);
            _infoTab.AddChild(_styles.MakeListPanel(body, verticalExpand: false));
            return;
        }

        var bulletinBody = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 6 };
        bulletinBody.AddChild(_styles.MakeText(bulletinText, expand: true));
        if (canEdit)
        {
            var change = _styles.MakeButton(Loc.GetString("company-pda-edit-bulletin"));
            change.OnPressed += _ =>
            {
                _editingBulletin = true;
                RebuildInfo();
            };
            bulletinBody.AddChild(change);
        }

        _infoTab.AddChild(_styles.MakeListPanel(bulletinBody, verticalExpand: false));
    }

    private void RebuildBank()
    {
        _bankTab.RemoveAllChildren();
        if (_state is not { HasCompany: true } state)
            return;

        var balances = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 4 };
        balances.AddChild(_styles.MakeHeading(Loc.GetString("company-pda-bank-balance", ("balance", state.BankBalance))));
        balances.AddChild(_styles.MakeText(Loc.GetString("company-pda-personal-balance", ("balance", state.PersonalBalance))));
        _bankTab.AddChild(_styles.MakeCard(balances));

        var amount = _styles.MakeLineEdit(Loc.GetString("company-pda-amount"));
        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6, Margin = new Thickness(4) };
        actions.AddChild(amount);

        if (state.IsOwner || (state.Permissions & CompanyPermission.BankDeposit) != 0)
        {
            var deposit = _styles.MakeButton(Loc.GetString("company-pda-deposit"));
            deposit.OnPressed += _ =>
            {
                if (int.TryParse(amount.Text, out var value))
                    Send(new CompanyManagementUiMessageEvent { Action = CompanyManagementUiAction.BankDeposit, Amount = value });
            };
            actions.AddChild(deposit);
        }

        if (state.IsOwner || (state.Permissions & CompanyPermission.BankWithdraw) != 0)
        {
            var withdraw = _styles.MakeButton(Loc.GetString("company-pda-withdraw"));
            withdraw.OnPressed += _ =>
            {
                if (int.TryParse(amount.Text, out var value))
                    Send(new CompanyManagementUiMessageEvent { Action = CompanyManagementUiAction.BankWithdraw, Amount = value });
            };
            actions.AddChild(withdraw);
        }

        _bankTab.AddChild(_styles.MakeActionPanel(actions));
    }

    private void RebuildRelations()
    {
        _relationsTab.RemoveAllChildren();
        if (_state is not { HasCompany: true } state)
            return;

        var wars = state.Relations.Where(r => r.Kind == CompanyRelationKind.War).ToList();
        var allies = state.Relations.Where(r => r.Kind == CompanyRelationKind.Alliance).ToList();

        var columns = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        columns.AddChild(BuildRelationColumn(
            Loc.GetString("company-pda-relations-war-column"),
            wars,
            state,
            Loc.GetString("company-pda-relations-war-empty")));
        columns.AddChild(BuildRelationColumn(
            Loc.GetString("company-pda-relations-alliance-column"),
            allies,
            state,
            Loc.GetString("company-pda-relations-alliance-empty")));

        _relationsTab.AddChild(columns);

        var canDeclare = state.IsOwner ||
            (state.Permissions & (CompanyPermission.DeclareWar | CompanyPermission.DeclareAlliance)) != 0;
        if (!canDeclare || state.InviteableCompanies.Count == 0)
            return;

        var pickerBody = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 6, Margin = new Thickness(4) };
        pickerBody.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-relations-pick")));

        var picker = new ItemList
        {
            SelectMode = ItemList.ItemListSelectMode.Single,
            MinHeight = 100,
            HorizontalExpand = true,
        };

        foreach (var entry in state.InviteableCompanies)
        {
            var item = picker.AddItem(entry.Name);
            item.Metadata = entry.Id;
            if (TryGetCompanyIcon(entry.IconId, out var tex))
                item.Icon = tex;
        }

        pickerBody.AddChild(picker);

        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        if (state.IsOwner || (state.Permissions & CompanyPermission.DeclareWar) != 0)
        {
            var war = _styles.MakeButton(Loc.GetString("company-pda-declare-war"));
            war.OnPressed += _ =>
            {
                if (!TryGetSelectedPickerId(picker, out var companyId))
                    return;
                Send(new CompanyManagementUiMessageEvent
                {
                    Action = CompanyManagementUiAction.SetRelation,
                    CompanyId = companyId,
                    RelationKind = CompanyRelationKind.War,
                });
            };
            actions.AddChild(war);
        }

        if (state.IsOwner || (state.Permissions & CompanyPermission.DeclareAlliance) != 0)
        {
            var ally = _styles.MakeButton(Loc.GetString("company-pda-declare-alliance"));
            ally.OnPressed += _ =>
            {
                if (!TryGetSelectedPickerId(picker, out var companyId))
                    return;
                Send(new CompanyManagementUiMessageEvent
                {
                    Action = CompanyManagementUiAction.SetRelation,
                    CompanyId = companyId,
                    RelationKind = CompanyRelationKind.Alliance,
                });
            };
            actions.AddChild(ally);
        }

        pickerBody.AddChild(actions);
        _relationsTab.AddChild(_styles.MakeActionPanel(pickerBody));
    }

    private Control BuildRelationColumn(
        string title,
        List<CompanyRelationData> entries,
        CompanyManagementUiState state,
        string emptyText)
    {
        var column = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
        header.AddChild(_styles.MakeSubHeading(title));
        header.AddChild(new Label
        {
            Text = entries.Count.ToString(),
            FontColorOverride = _styles.Theme.Text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        column.AddChild(header);

        var list = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 2, Margin = new Thickness(4) };
        if (entries.Count == 0)
        {
            list.AddChild(_styles.MakeText(emptyText));
        }
        else
        {
            foreach (var rel in entries)
            {
                var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 4 };
                if (TryGetCompanyIcon(rel.IconId, out var tex))
                {
                    row.AddChild(new TextureRect
                    {
                        Texture = tex,
                        SetSize = new System.Numerics.Vector2(18, 18),
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        VerticalAlignment = VAlignment.Center,
                    });
                }

                row.AddChild(_styles.MakeText(rel.OtherCompanyName, expand: true));

                if (state.IsOwner ||
                    (state.Permissions & (CompanyPermission.DeclareWar | CompanyPermission.DeclareAlliance)) != 0)
                {
                    var clear = _styles.MakeButton(Loc.GetString("company-pda-clear-relation"));
                    var other = rel.OtherCompany.Id;
                    clear.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
                    {
                        Action = CompanyManagementUiAction.ClearRelation,
                        CompanyId = other,
                    });
                    row.AddChild(clear);
                }

                list.AddChild(_styles.MakeEntry(row));
            }
        }

        column.AddChild(_styles.MakeListPanel(list, verticalExpand: false));
        return column;
    }

    private static bool TryGetSelectedPickerId(ItemList picker, out string companyId)
    {
        companyId = string.Empty;
        for (var i = 0; i < picker.Count; i++)
        {
            var item = picker[i];
            if (!item.Selected || item.Metadata is not string id)
                continue;
            companyId = id;
            return true;
        }

        return false;
    }

    private bool TryGetCompanyIcon(string? iconId, out Texture texture)
    {
        texture = default!;
        if (string.IsNullOrWhiteSpace(iconId))
            return false;
        if (!_proto.TryIndex<CompanyIconPrototype>(iconId, out var icon))
            return false;

        texture = _sprite.Frame0(icon.Icon);
        return true;
    }

    private void RebuildRoster()
    {
        _rosterTab.RemoveAllChildren();
        if (_state is not { HasCompany: true } state)
            return;

        if (state.IsOwner || (state.Permissions & CompanyPermission.Invite) != 0)
        {
            var inviteName = _styles.MakeLineEdit(Loc.GetString("company-pda-invite-player"));
            var inviteBtn = _styles.MakeButton(Loc.GetString("company-pda-invite"));
            inviteBtn.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.InvitePlayer,
                Text = inviteName.Text,
            });

            var inviteRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                Margin = new Thickness(4),
            };
            inviteRow.AddChild(inviteName);
            inviteRow.AddChild(inviteBtn);
            _rosterTab.AddChild(_styles.MakeActionPanel(inviteRow));
        }

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4) };
        header.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-tab-roster")));
        header.AddChild(new Label
        {
            Text = state.Roster.Count.ToString(),
            FontColorOverride = _styles.Theme.Text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        _rosterTab.AddChild(header);

        var list = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 2, Margin = new Thickness(4) };
        if (state.Roster.Count == 0)
        {
            list.AddChild(_styles.MakeText(Loc.GetString("company-pda-roster-empty")));
        }
        else
        {
            foreach (var member in state.Roster)
                list.AddChild(BuildMemberCard(member, state));
        }

        _rosterTab.AddChild(_styles.MakeListPanel(list));
    }

    private Control BuildMemberCard(CompanyMemberData member, CompanyManagementUiState state)
    {
        var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 4 };

        var nameRow = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        var name = member.CharacterName ?? member.PlayerName;
        if (member.Owner)
            name += $" [{Loc.GetString("company-pda-leader-tag")}]";
        nameRow.AddChild(_styles.MakeHeading(name));
        if (member.Online)
        {
            nameRow.AddChild(new Label
            {
                Text = "●",
                FontColorOverride = _styles.Theme.TabActive,
                HorizontalAlignment = HAlignment.Right,
                HorizontalExpand = true,
            });
        }

        body.AddChild(nameRow);
        body.AddChild(_styles.MakeText(
            $"{member.RoleName} — {Loc.GetString($"company-pda-access-{member.AccessTier.ToString().ToLowerInvariant()}")}"));

        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 4 };

        if (!member.Owner && (state.IsOwner || (state.Permissions & CompanyPermission.Kick) != 0))
        {
            var kick = _styles.MakeButton(Loc.GetString("company-pda-kick"));
            var id = member.PlayerUserId;
            var slot = member.CharacterSlot;
            kick.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.KickMember,
                GuidValue = id,
                CharacterSlot = slot,
            });
            actions.AddChild(kick);
        }

        if (state.Roles.Count > 0 &&
            (state.IsOwner || (state.Permissions & CompanyPermission.ManageRoles) != 0 ||
             (state.Permissions & CompanyPermission.AssignAccess) != 0))
        {
            var roleOpt = new OptionButton { MinWidth = 120 };
            _styles.StyleOption(roleOpt);
            for (var i = 0; i < state.Roles.Count; i++)
                roleOpt.AddItem(state.Roles[i].Name, i);

            var assign = _styles.MakeButton(Loc.GetString("company-pda-assign-role"));
            var playerId = member.PlayerUserId;
            var memberSlot = member.CharacterSlot;
            assign.OnPressed += _ =>
            {
                if (roleOpt.SelectedId < 0 || roleOpt.SelectedId >= state.Roles.Count)
                    return;
                Send(new CompanyManagementUiMessageEvent
                {
                    Action = CompanyManagementUiAction.AssignRole,
                    GuidValue = playerId,
                    GuidValue2 = state.Roles[roleOpt.SelectedId].RoleId,
                    CharacterSlot = memberSlot,
                });
            };
            actions.AddChild(roleOpt);
            actions.AddChild(assign);
        }

        if (actions.ChildCount > 0)
        {
            body.AddChild(_styles.MakeDivider());
            body.AddChild(actions);
        }

        var card = _styles.MakeCard(body);
        if (member.Online)
        {
            card.PanelOverride = _styles.MakePanelBox(
                _styles.Theme.MemberAliveBackground,
                _styles.Theme.MemberAliveBorder,
                2,
                new Thickness(8, 6, 8, 6));
        }

        return card;
    }

    private void RebuildLogs()
    {
        _logsTab.RemoveAllChildren();
        if (_state is not { } state)
            return;

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4) };
        header.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-tab-logs")));
        header.AddChild(new Label
        {
            Text = state.Logs.Count.ToString(),
            FontColorOverride = _styles.Theme.Text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        _logsTab.AddChild(header);

        var list = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 2, Margin = new Thickness(4) };
        if (state.Logs.Count == 0)
        {
            list.AddChild(_styles.MakeText(Loc.GetString("company-pda-logs-none")));
        }
        else
        {
            foreach (var log in state.Logs)
            {
                list.AddChild(_styles.MakeEntry(_styles.MakeText($"[{log.LogType}] {log.Message}", expand: true)));
            }
        }

        _logsTab.AddChild(_styles.MakeListPanel(list));
    }

    private void RebuildInvites()
    {
        _invitesTab.RemoveAllChildren();
        if (_state is not { } state)
            return;

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4) };
        header.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-tab-invites")));
        header.AddChild(new Label
        {
            Text = state.Invitations.Count.ToString(),
            FontColorOverride = _styles.Theme.Text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        _invitesTab.AddChild(header);

        var list = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 2, Margin = new Thickness(4) };
        if (state.Invitations.Count == 0)
        {
            list.AddChild(_styles.MakeText(Loc.GetString("company-pda-invites-none")));
        }
        else
        {
            foreach (var inv in state.Invitations)
                list.AddChild(BuildInviteCard(inv));
        }

        _invitesTab.AddChild(_styles.MakeListPanel(list));
    }

    private Control BuildInviteCard(CompanyInvitationData inv)
    {
        var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 4 };
        body.AddChild(_styles.MakeText(
            inv.Incoming
                ? Loc.GetString("company-pda-invite-incoming", ("company", inv.CompanyName), ("from", inv.FromUserName))
                : Loc.GetString("company-pda-invite-outgoing", ("company", inv.CompanyName), ("to", inv.TargetUserName)),
            expand: true));

        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 4 };
        if (inv.Incoming)
        {
            var accept = _styles.MakeButton(Loc.GetString("company-pda-accept"));
            var decline = _styles.MakeButton(Loc.GetString("company-pda-decline"));
            var id = inv.InviteId;
            accept.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.AcceptInvite,
                GuidValue = id,
            });
            decline.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.DeclineInvite,
                GuidValue = id,
            });
            actions.AddChild(accept);
            actions.AddChild(decline);
        }
        else
        {
            var cancel = _styles.MakeButton(Loc.GetString("company-pda-cancel"));
            var id = inv.InviteId;
            cancel.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.CancelInvite,
                GuidValue = id,
            });
            actions.AddChild(cancel);
        }

        body.AddChild(actions);
        return _styles.MakeCard(body);
    }

    private void RebuildRoles()
    {
        _rolesTab.RemoveAllChildren();
        if (_state is not { HasCompany: true } state)
            return;

        var canManage = state.IsOwner || (state.Permissions & CompanyPermission.ManageRoles) != 0;
        var grantable = state.IsOwner ? CompanyPermission.All : state.Permissions;

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4) };
        header.AddChild(_styles.MakeSubHeading(Loc.GetString("company-pda-tab-roles")));
        header.AddChild(new Label
        {
            Text = state.Roles.Count.ToString(),
            FontColorOverride = _styles.Theme.Text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
        });
        _rolesTab.AddChild(header);

        var list = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 2, Margin = new Thickness(4) };
        if (state.Roles.Count == 0)
            list.AddChild(_styles.MakeText(Loc.GetString("company-pda-roles-empty")));

        foreach (var role in state.Roles)
            list.AddChild(BuildRoleCard(role, canManage, grantable));

        _rolesTab.AddChild(_styles.MakeListPanel(list));

        if (!canManage)
            return;

        var createBody = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 4, Margin = new Thickness(4) };
        createBody.AddChild(_styles.MakeHeading(Loc.GetString("company-pda-create-role")));
        var createEditor = BuildRoleEditor(string.Empty, CompanyAccessTier.Low, CompanyPermission.MemberDefault, grantable);
        createEditor.NameEdit.PlaceHolder = Loc.GetString("company-pda-role-name");
        createBody.AddChild(createEditor.Root);

        var create = _styles.MakeButton(Loc.GetString("company-pda-create-role"));
        create.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(createEditor.NameEdit.Text))
                return;
            Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.CreateRole,
                Text = createEditor.NameEdit.Text,
                AccessTier = createEditor.GetTier(),
                Permissions = createEditor.GetPermissions(),
            });
        };
        createBody.AddChild(create);
        _rolesTab.AddChild(_styles.MakeActionPanel(createBody));
    }

    private Control BuildRoleCard(CompanyRoleData role, bool canManage, CompanyPermission grantable)
    {
        var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, SeparationOverride = 4 };

        var title = $"{role.Name} — {Loc.GetString($"company-pda-access-{role.AccessTier.ToString().ToLowerInvariant()}")}{(role.IsDefault ? " *" : "")}";
        body.AddChild(_styles.MakeHeading(title));

        var flagsLabel = string.Join(", ",
            EditablePermissions
                .Where(p => (role.Permissions & p) != 0)
                .Select(p => Loc.GetString($"company-pda-perm-{p.ToString().ToLowerInvariant()}")));
        body.AddChild(_styles.MakeText(string.IsNullOrEmpty(flagsLabel)
            ? Loc.GetString("company-pda-perm-none")
            : flagsLabel));

        if (!canManage)
            return _styles.MakeCard(body);

        body.AddChild(_styles.MakeDivider());
        var editor = BuildRoleEditor(role.Name, role.AccessTier, role.Permissions, grantable);
        body.AddChild(editor.Root);

        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 4 };
        var save = _styles.MakeButton(Loc.GetString("company-pda-save-role"));
        var roleId = role.RoleId;
        save.OnPressed += _ =>
        {
            Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.UpdateRole,
                GuidValue = roleId,
                Text = editor.NameEdit.Text,
                AccessTier = editor.GetTier(),
                Permissions = editor.GetPermissions(),
            });
        };
        actions.AddChild(save);

        if (!role.IsDefault)
        {
            var del = _styles.MakeButton(Loc.GetString("company-pda-delete-role"));
            del.OnPressed += _ => Send(new CompanyManagementUiMessageEvent
            {
                Action = CompanyManagementUiAction.DeleteRole,
                GuidValue = roleId,
            });
            actions.AddChild(del);
        }

        body.AddChild(actions);
        return _styles.MakeCard(body);
    }

    private RoleEditor BuildRoleEditor(
        string name,
        CompanyAccessTier tier,
        CompanyPermission permissions,
        CompanyPermission grantable)
    {
        var root = new BoxContainer { Orientation = LayoutOrientation.Vertical, Margin = new Thickness(0, 0, 0, 2), SeparationOverride = 3 };
        var nameEdit = _styles.MakeLineEdit(text: name);
        root.AddChild(nameEdit);

        var tierBtn = new OptionButton();
        _styles.StyleOption(tierBtn);
        tierBtn.AddItem(Loc.GetString("company-pda-access-low"), (int)CompanyAccessTier.Low);
        tierBtn.AddItem(Loc.GetString("company-pda-access-medium"), (int)CompanyAccessTier.Medium);
        tierBtn.AddItem(Loc.GetString("company-pda-access-high"), (int)CompanyAccessTier.High);
        tierBtn.SelectId((int)tier);
        root.AddChild(tierBtn);

        var checks = new Dictionary<CompanyPermission, CheckBox>();
        foreach (var perm in EditablePermissions)
        {
            if ((grantable & perm) == 0)
                continue;

            var box = new CheckBox
            {
                Text = Loc.GetString($"company-pda-perm-{perm.ToString().ToLowerInvariant()}"),
                Pressed = (permissions & perm) != 0,
            };
            _styles.StyleCheckBox(box);
            checks[perm] = box;
            root.AddChild(box);
        }

        return new RoleEditor(root, nameEdit, tierBtn, checks);
    }

    private sealed class RoleEditor
    {
        public BoxContainer Root { get; }
        public LineEdit NameEdit { get; }
        private readonly OptionButton _tier;
        private readonly Dictionary<CompanyPermission, CheckBox> _checks;

        public RoleEditor(
            BoxContainer root,
            LineEdit nameEdit,
            OptionButton tier,
            Dictionary<CompanyPermission, CheckBox> checks)
        {
            Root = root;
            NameEdit = nameEdit;
            _tier = tier;
            _checks = checks;
        }

        public CompanyAccessTier GetTier() =>
            (CompanyAccessTier)Math.Max((int)CompanyAccessTier.Low, _tier.SelectedId);

        public CompanyPermission GetPermissions()
        {
            var result = CompanyPermission.None;
            foreach (var (perm, box) in _checks)
            {
                if (box.Pressed)
                    result |= perm;
            }

            return result;
        }
    }

    private void Send(CompanyManagementUiMessageEvent ev) => OnMessage?.Invoke(ev);
}
