using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Forge.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class ToggleLoadoutButton : Button;
