using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._Forge.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiCustomizationWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<string, ProtoId<StationAiScreenPrototype>, Color>? OnApply;

    private readonly Dictionary<ProtoId<StationAiScreenPrototype>, (Button Button, AnimatedTextureRect Preview)> _screens = new();
    private readonly ButtonGroup _screenGroup = new(false);
    private ProtoId<StationAiScreenPrototype> _selectedScreen = "StationAiScreenDefault";
    private TimeSpan _cooldownEnd;

    public StationAiCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        NameEdit.IsValid = text => text.Length <= 32;
        ColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

        foreach (var screen in _prototypes.EnumeratePrototypes<StationAiScreenPrototype>().OrderBy(screen => screen.ID))
        {
            AddScreen(screen);
        }

        ColorSelector.OnColorChanged += UpdatePreviewColors;
        ApplyButton.OnPressed += _ =>
        {
            if (_screens.ContainsKey(_selectedScreen))
                OnApply?.Invoke(NameEdit.Text, _selectedScreen, ColorSelector.Color.WithAlpha(1f));
        };
    }

    private void AddScreen(StationAiScreenPrototype screen)
    {
        var name = Loc.GetString(screen.Name);
        var button = new Button
        {
            MinSize = new Vector2(135, 104),
            HorizontalExpand = true,
            ToggleMode = true,
            Group = _screenGroup,
            ToolTip = name,
        };

        var preview = new AnimatedTextureRect
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        preview.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(screen.Sprite, screen.State));
        preview.DisplayRect.Stretch = TextureRect.StretchMode.KeepCentered;
        preview.DisplayRect.TextureScale = new Vector2(2f, 2f);

        var label = new Label
        {
            Text = name,
            ClipText = true,
            HorizontalAlignment = HAlignment.Center,
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        content.AddChild(preview);
        content.AddChild(label);
        button.AddChild(content);

        button.OnPressed += _ => _selectedScreen = screen.ID;
        ScreenGrid.AddChild(button);
        _screens.Add(screen.ID, (button, preview));
    }

    public void UpdateState(StationAiCustomizationState state)
    {
        NameEdit.Text = state.Name;
        if (_screens.ContainsKey(state.Screen))
            _selectedScreen = state.Screen;

        if (_screens.TryGetValue(_selectedScreen, out var selected))
            selected.Button.Pressed = true;

        ColorSelector.Color = state.Color;
        UpdatePreviewColors(state.Color);
        _cooldownEnd = _timing.CurTime + TimeSpan.FromSeconds(state.CooldownSeconds);
        UpdateCooldown();
    }

    private void UpdatePreviewColors(Color color)
    {
        color = color.WithAlpha(1f);
        foreach (var (_, preview) in _screens.Values)
            preview.DisplayRect.Modulate = color;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldown();
    }

    private void UpdateCooldown()
    {
        var remaining = Math.Max(0, (int) Math.Ceiling((_cooldownEnd - _timing.CurTime).TotalSeconds));
        ApplyButton.Disabled = remaining > 0;
        CooldownLabel.Visible = remaining > 0;
        CooldownLabel.Text = remaining > 0
            ? Loc.GetString("station-ai-customization-cooldown", ("seconds", remaining))
            : string.Empty;
    }
}
