using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;

namespace Content.Client._Forge.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiCustomizationWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<string, ProtoId<StationAiScreenPrototype>>? OnApply;

    private readonly Dictionary<int, ProtoId<StationAiScreenPrototype>> _screens = new();
    private TimeSpan _cooldownEnd;

    public StationAiCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        NameEdit.IsValid = text => text.Length <= 32;

        var index = 0;
        foreach (var screen in _prototypes.EnumeratePrototypes<StationAiScreenPrototype>().OrderBy(screen => screen.ID))
        {
            _screens[index] = screen.ID;
            ScreenOptions.AddItem(Loc.GetString(screen.Name), index++);
        }

        ScreenOptions.OnItemSelected += args => ScreenOptions.SelectId(args.Id);
        ApplyButton.OnPressed += _ =>
        {
            if (_screens.TryGetValue(ScreenOptions.SelectedId, out var screen))
                OnApply?.Invoke(NameEdit.Text, screen);
        };
    }

    public void UpdateState(StationAiCustomizationState state)
    {
        NameEdit.Text = state.Name;
        var selected = _screens.FirstOrDefault(pair => pair.Value == state.Screen).Key;
        ScreenOptions.TrySelectId(selected);
        _cooldownEnd = _timing.CurTime + TimeSpan.FromSeconds(state.CooldownSeconds);
        UpdateCooldown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldown();
    }

    private void UpdateCooldown()
    {
        var remaining = Math.Max(0, (int) Math.Ceiling((_cooldownEnd - _timing.CurTime).TotalSeconds));
        ApplyButton.Disabled = remaining > 0;
        CooldownLabel.Visible = remaining > 0;
        CooldownLabel.Text = remaining > 0
            ? Loc.GetString("station-ai-customization-cooldown", ("seconds", remaining))
            : string.Empty;
    }
}
