using Content.Shared._Forge.Shipyard;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipBrokerWindow : FancyWindow
{
    private readonly ShipBrokerBoundUserInterface _owner;

    public ShipBrokerWindow(ShipBrokerBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        _owner = owner;
        SetPriceButton.OnPressed += _ =>
        {
            if (int.TryParse(PriceEdit.Text, out var price))
                _owner.SendPrice(price);
        };
        ConfirmButton.OnPressed += _ => _owner.SendConfirm();
    }

    public void UpdateState(ShipBrokerBoundUserInterfaceState state)
    {
        VesselLabel.Text = state.VesselName ?? Loc.GetString("ship-broker-ui-no-vessel");
        AppraisalLabel.Text = state.Appraisal != null
            ? Loc.GetString("ship-broker-ui-appraisal", ("value", state.Appraisal.Value))
            : "";
        ConfirmButton.Disabled = !state.SellerPresent || !state.BuyerPresent || state.ListedPrice == null;
    }
}
