using System.Linq;
using Content.Shared._Forge.Shipyard;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipFabricatorWindow : FancyWindow
{
    private readonly ShipFabricatorBoundUserInterface _owner;

    public ShipFabricatorWindow(ShipFabricatorBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        _owner = owner;
        StartButton.OnPressed += _ => _owner.SendStart();
        EjectButton.OnPressed += _ => _owner.SendEject();
    }

    public void UpdateState(ShipFabricatorBoundUserInterfaceState state)
    {
        VesselLabel.Text = state.VesselName ?? Loc.GetString("ship-fabricator-ui-no-blueprint");
        StatusLabel.Text = state.Fabricating
            ? Loc.GetString("ship-fabricator-ui-fabricating", ("time", state.RemainingTime.TotalSeconds.ToString("F0")))
            : Loc.GetString("ship-fabricator-ui-ready");

        var mats = string.Join("\n", state.MaterialRequirements.Select(kv =>
        {
            state.MaterialStored.TryGetValue(kv.Key, out var have);
            return $"{kv.Key}: {have}/{kv.Value}";
        }));
        MaterialsLabel.SetMessage(mats);
        var hasMaterials = state.MaterialRequirements.Count == 0
            || state.MaterialRequirements.All(kv =>
                state.MaterialStored.TryGetValue(kv.Key, out var have) && have >= kv.Value);

        StartButton.Disabled = state.Fabricating || state.Vessel == null || !hasMaterials;
        EjectButton.Disabled = state.Fabricating || !state.HasBlueprint;
    }
}
