using System.Collections.Generic;
using Content.Shared._Forge.Botany.HydroponicsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Forge.Botany.HydroponicsConsole;

[GenerateTypedNameReferences]
public sealed partial class HydroponicsConsoleWindow : FancyWindow
{
    public HydroponicsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(HydroponicsConsoleBoundUserInterfaceState state)
    {
        TrayContainer.DisposeAllChildren();

        if (state.Trays.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("hydroponics-console-no-trays");
            return;
        }

        StatusLabel.Text = Loc.GetString("hydroponics-console-tray-count", ("count", state.Trays.Count));

        foreach (var tray in state.Trays)
        {
            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 10)
            };

            var header = tray.HasPlant
                ? Loc.GetString("hydroponics-console-tray-header",
                    ("tray", tray.TrayName),
                    ("plant", tray.PlantName),
                    ("address", string.IsNullOrEmpty(tray.Address) ? "-" : tray.Address))
                : Loc.GetString("hydroponics-console-tray-empty",
                    ("tray", tray.TrayName),
                    ("address", string.IsNullOrEmpty(tray.Address) ? "-" : tray.Address));

            box.AddChild(new Label { Text = header });

            if (tray.HasPlant)
            {
                var status = tray.Dead
                    ? Loc.GetString("hydroponics-console-status-dead")
                    : tray.Harvest
                        ? Loc.GetString("hydroponics-console-status-harvest")
                        : Loc.GetString("hydroponics-console-status-growing");

                box.AddChild(new Label
                {
                    Text = Loc.GetString("hydroponics-console-tray-stats",
                        ("status", status),
                        ("health", $"{tray.Health:0}"),
                        ("endurance", $"{tray.Endurance:0}"),
                        ("age", tray.Age),
                        ("water", $"{tray.Water:0}"),
                        ("nutrition", $"{tray.Nutrition:0}"),
                        ("toxins", $"{tray.Toxins:0}"),
                        ("weeds", $"{tray.Weeds:0.#}"),
                        ("pests", $"{tray.Pests:0.#}"))
                });

                var warnings = new List<string>();
                if (tray.ImproperHeat)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-heat"));
                if (tray.ImproperPressure)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-pressure"));
                if (tray.ImproperLight)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-light"));
                if (tray.MissingGas)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-gas"));
                if (tray.Radioactive)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-radiation"));
                if (tray.CarnivorousGrab)
                    warnings.Add(Loc.GetString("hydroponics-console-warn-grab"));

                if (warnings.Count > 0)
                {
                    box.AddChild(new Label
                    {
                        Text = Loc.GetString("hydroponics-console-warnings", ("warnings", string.Join(", ", warnings)))
                    });
                }

                box.AddChild(new Label
                {
                    Text = Loc.GetString("hydroponics-console-atmos",
                        ("heat", $"{tray.IdealHeat:0}"),
                        ("heatTol", $"{tray.HeatTolerance:0.#}"),
                        ("lowP", $"{tray.LowPressure:0}"),
                        ("highP", $"{tray.HighPressure:0}"),
                        ("consume", string.IsNullOrEmpty(tray.ConsumeGases)
                            ? Loc.GetString("plant-analyzer-plant-gases-none")
                            : tray.ConsumeGases),
                        ("exude", string.IsNullOrEmpty(tray.ExudeGases)
                            ? Loc.GetString("plant-analyzer-plant-gases-none")
                            : tray.ExudeGases))
                });

                var chems = tray.Chemicals.Length == 0
                    ? "-"
                    : string.Join(", ", tray.Chemicals);
                var mutations = tray.Mutations.Length == 0
                    ? "-"
                    : string.Join(", ", tray.Mutations);

                box.AddChild(new Label
                {
                    Text = Loc.GetString("hydroponics-console-genes", ("chems", chems), ("mutations", mutations))
                });
            }

            TrayContainer.AddChild(box);
        }
    }
}
