using System.Linq;
using System.Numerics;
using Content.Client._Forge.Botany.UI;
using Content.Client.GameTicking.Managers;
using Content.Shared._Forge.Botany.HydroponicsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Maths;

namespace Content.Client._Forge.Botany.HydroponicsConsole;

[GenerateTypedNameReferences]
public sealed partial class HydroponicsConsoleWindow : BaseWindow
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _systems = default!;

    private readonly BotanyUiStyles _styles;
    private readonly ClientGameTicker _ticker;
    private readonly List<HydroponicsConsoleTrayEntry> _trays = new();
    private NetEntity? _selected;

    public HydroponicsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _styles = new BotanyUiStyles(_resCache);
        _ticker = _systems.GetEntitySystem<ClientGameTicker>();

        TitleLabel.Text = Loc.GetString("hydroponics-console-title");
        SubtitleLabel.Text = Loc.GetString("hydroponics-console-subtitle");
        DetailHeader.Text = Loc.GetString("hydroponics-console-detail-header");
        ListHeader.Text = Loc.GetString("hydroponics-console-list-header");
        OsLabel.Text = Loc.GetString("hydroponics-console-os");

        CloseButton.OnPressed += _ => Close();
        ApplyChrome();
        ShowEmptyDetails();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        TimeLabel.Text = stationTime.ToString(@"hh\:mm\:ss");
    }

    public void Populate(HydroponicsConsoleBoundUserInterfaceState state)
    {
        _trays.Clear();
        _trays.AddRange(state.Trays);

        if (_selected is { } selected && _trays.All(t => t.Entity != selected))
            _selected = null;

        if (_selected == null && _trays.Count > 0)
            _selected = _trays[0].Entity;

        StatusLabel.Text = _trays.Count == 0
            ? Loc.GetString("hydroponics-console-no-trays")
            : Loc.GetString("hydroponics-console-tray-count", ("count", _trays.Count));
        ListCountLabel.Text = _trays.Count.ToString();

        RebuildList();
        ShowSelectedDetails();
    }

    private void RebuildList()
    {
        var scroll = ListScroll.VScrollTarget;
        ListContainer.DisposeAllChildren();

        if (_trays.Count == 0)
        {
            ListContainer.AddChild(_styles.Sub(Loc.GetString("hydroponics-console-list-empty")));
            return;
        }

        foreach (var tray in _trays)
        {
            var button = new BotanyListButton(_styles) { Key = tray.Entity };
            var title = string.IsNullOrEmpty(tray.Address) ? tray.TrayName : $"[{tray.Address}]";
            string subtitle;
            Color subtitleColor;

            if (!tray.HasPlant)
            {
                subtitle = Loc.GetString("hydroponics-console-list-empty-tray");
                subtitleColor = BotanyUiTheme.Empty;
            }
            else if (tray.Dead)
            {
                subtitle = $"{tray.PlantName} — {Loc.GetString("hydroponics-console-status-dead")}";
                subtitleColor = BotanyUiTheme.Danger;
            }
            else if (tray.Harvest)
            {
                subtitle = $"{tray.PlantName} — {Loc.GetString("hydroponics-console-status-harvest")}";
                subtitleColor = BotanyUiTheme.Harvest;
            }
            else
            {
                subtitle = $"{tray.PlantName} — {Loc.GetString("hydroponics-console-status-growing")}  HP {tray.Health:0}/{tray.Endurance:0}";
                subtitleColor = TrayHealthColor(tray);
            }

            button.SetContent(title, subtitle, subtitleColor);
            button.ApplySelected(_selected == tray.Entity);
            var captured = tray.Entity;
            button.OnPressed += _ =>
            {
                _selected = captured;
                RebuildList();
                ShowSelectedDetails();
            };
            ListContainer.AddChild(button);
        }

        ListScroll.VScrollTarget = scroll;
    }

    private void ShowSelectedDetails()
    {
        DetailContainer.DisposeAllChildren();

        var tray = _trays.FirstOrDefault(t => t.Entity == _selected);
        if (tray == null)
        {
            ShowEmptyDetails();
            return;
        }

        var name = tray.HasPlant ? tray.PlantName : Loc.GetString("hydroponics-console-list-empty-tray");
        DetailContainer.AddChild(_styles.Heading($"{tray.TrayName}  [{(string.IsNullOrEmpty(tray.Address) ? "-" : tray.Address)}]"));
        DetailContainer.AddChild(_styles.Body(name, 14, tray.HasPlant ? BotanyUiTheme.Ok : BotanyUiTheme.Empty));

        if (!tray.HasPlant)
        {
            DetailContainer.AddChild(_styles.Sub(Loc.GetString("hydroponics-console-detail-empty")));
            return;
        }

        var status = tray.Dead
            ? Loc.GetString("hydroponics-console-status-dead")
            : tray.Harvest
                ? Loc.GetString("hydroponics-console-status-harvest")
                : Loc.GetString("hydroponics-console-status-growing");
        var statusColor = tray.Dead ? BotanyUiTheme.Danger : tray.Harvest ? BotanyUiTheme.Harvest : BotanyUiTheme.Ok;

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-section-status")));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-status"), status, statusColor));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-health"), $"{tray.Health:0} / {tray.Endurance:0}", TrayHealthColor(tray)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-age"), tray.Age.ToString()));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-water"), $"{tray.Water:0}", LevelColor(tray.Water, 15)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-nutrition"), $"{tray.Nutrition:0}", LevelColor(tray.Nutrition, 8)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-toxins"), $"{tray.Toxins:0}", tray.Toxins >= 40 ? BotanyUiTheme.Danger : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-weeds"), $"{tray.Weeds:0.#}", tray.Weeds >= 5 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-pests"), $"{tray.Pests:0.#}", tray.Pests >= 5 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));

        var warnings = new List<string>();
        if (tray.ImproperHeat)
            warnings.Add(Loc.GetString("hydroponics-console-warn-heat"));
        if (tray.ImproperPressure)
            warnings.Add(Loc.GetString("hydroponics-console-warn-pressure"));
        if (tray.ImproperLight)
            warnings.Add(Loc.GetString("hydroponics-console-warn-light"));
        if (tray.MissingGas)
            warnings.Add(Loc.GetString("hydroponics-console-warn-gas"));
        if (tray.Radioactive)
            warnings.Add(Loc.GetString("hydroponics-console-warn-radiation"));
        if (tray.CarnivorousGrab)
            warnings.Add(Loc.GetString("hydroponics-console-warn-grab"));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-section-warnings")));
        DetailContainer.AddChild(warnings.Count == 0
            ? _styles.Body(Loc.GetString("hydroponics-console-warnings-none"), 12, BotanyUiTheme.Ok)
            : _styles.Body(string.Join(" · ", warnings), 12, BotanyUiTheme.Warning));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-section-atmos")));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-heat"), $"{tray.IdealHeat:0} K ± {tray.HeatTolerance:0.#}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-pressure"), $"{tray.LowPressure:0} – {tray.HighPressure:0} kPa"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-consume"),
            string.IsNullOrEmpty(tray.ConsumeGases) ? Loc.GetString("plant-analyzer-plant-gases-none") : tray.ConsumeGases));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-exude"),
            string.IsNullOrEmpty(tray.ExudeGases) ? Loc.GetString("plant-analyzer-plant-gases-none") : tray.ExudeGases));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-section-genes")));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-chems"),
            tray.Chemicals.Length == 0 ? "—" : string.Join(", ", tray.Chemicals)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-mutations"),
            tray.Mutations.Length == 0 ? "—" : string.Join(", ", tray.Mutations)));
    }

    private void ShowEmptyDetails()
    {
        DetailContainer.DisposeAllChildren();
        DetailContainer.AddChild(_styles.Sub(Loc.GetString("hydroponics-console-detail-none")));
    }

    private static Color TrayHealthColor(HydroponicsConsoleTrayEntry tray)
    {
        if (tray.Dead || tray.Endurance <= 0)
            return BotanyUiTheme.Danger;
        var ratio = tray.Health / tray.Endurance;
        if (ratio <= 0.25f)
            return BotanyUiTheme.Danger;
        if (ratio <= 0.5f)
            return BotanyUiTheme.Warning;
        return BotanyUiTheme.Ok;
    }

    private static Color LevelColor(float value, float low)
    {
        return value <= low ? BotanyUiTheme.Warning : BotanyUiTheme.Text;
    }

    private void ApplyChrome()
    {
        Background.ModulateSelfOverride = BotanyUiTheme.WindowBackground;
        Border.ModulateSelfOverride = BotanyUiTheme.WindowBorder;
        CloseButton.ModulateSelfOverride = BotanyUiTheme.CloseButton;
        ContentBorder.ModulateSelfOverride = BotanyUiTheme.ContentBorder;
        ContentBackground.ModulateSelfOverride = BotanyUiTheme.ContentBackground;

        TitleLabel.FontOverride = _styles.GetBoldFont(18);
        TitleLabel.FontColorOverride = BotanyUiTheme.Heading;
        TimeLabel.FontOverride = _styles.GetBoldFont(16);
        TimeLabel.FontColorOverride = BotanyUiTheme.Heading;
        SubtitleLabel.FontOverride = _styles.GetRegularFont(12);
        SubtitleLabel.FontColorOverride = BotanyUiTheme.SubText;
        StatusLabel.FontOverride = _styles.GetRegularFont(12);
        StatusLabel.FontColorOverride = BotanyUiTheme.Text;
        DetailHeader.FontOverride = _styles.GetBoldFont(13);
        DetailHeader.FontColorOverride = BotanyUiTheme.Heading;
        ListHeader.FontOverride = _styles.GetBoldFont(13);
        ListHeader.FontColorOverride = BotanyUiTheme.Heading;
        ListCountLabel.FontOverride = _styles.GetRegularFont(12);
        ListCountLabel.FontColorOverride = BotanyUiTheme.Text;
        OsLabel.FontOverride = _styles.GetRegularFont(11);
        OsLabel.FontColorOverride = BotanyUiTheme.SubText;

        BotanyUiStyles.ApplyPanel(MainDivider, BotanyUiTheme.Divider, BotanyUiTheme.Divider, 0);
        BotanyUiStyles.ApplyPanel(DetailPanel, BotanyUiTheme.ListBackground, BotanyUiTheme.ListBorder);
        BotanyUiStyles.ApplyPanel(ListPanel, BotanyUiTheme.ListBackground, BotanyUiTheme.ListBorder);
    }
}
